; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=aarch64 -verify-machineinstrs < %s | FileCheck %s --check-prefix=CHECK
;
; Tests that relaxed (monotonic) atomic loads/stores are paired into LDP/STP,
; while volatile and acquire/release atomics are NOT paired.
;
; On AArch64, a relaxed atomic load/store is just a regular LDR/STR (no barrier).
; LDP/STP performs two independent 8-byte accesses — each individually atomic —
; so pairing a relaxed atomic with a non-atomic (or another relaxed atomic) is
; semantically safe.  Acquire/release/seq_cst need LDAR/STLR which LDP/STP
; cannot provide, so they must NOT be paired.

;--- load: relaxed atomic first, then plain → LDP
define i64 @load_relaxed_then_plain(ptr %p) {
; CHECK-LABEL: load_relaxed_then_plain:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ldp x[[R0:[0-9]+]], x[[R1:[0-9]+]], [x0]
; CHECK-NEXT:    add x0, x[[R0]], x[[R1]]
; CHECK-NEXT:    ret
  %a = load atomic i64, ptr %p monotonic, align 8
  %q = getelementptr i8, ptr %p, i64 8
  %b = load i64, ptr %q, align 8
  %r = add i64 %a, %b
  ret i64 %r
}

;--- load: two relaxed atomic → LDP
define i64 @load_two_relaxed(ptr %p) {
; CHECK-LABEL: load_two_relaxed:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ldp x[[R0:[0-9]+]], x[[R1:[0-9]+]], [x0]
; CHECK-NEXT:    add x0, x[[R0]], x[[R1]]
; CHECK-NEXT:    ret
  %a = load atomic i64, ptr %p monotonic, align 8
  %q = getelementptr i8, ptr %p, i64 8
  %b = load atomic i64, ptr %q monotonic, align 8
  %r = add i64 %a, %b
  ret i64 %r
}

;--- load: acquire atomic → must NOT pair (needs LDAR)
define i64 @load_acquire_then_plain(ptr %p) {
; CHECK-LABEL: load_acquire_then_plain:
; CHECK:       // %bb.0:
; CHECK-NOT:     ldp
; CHECK:         ldar
; CHECK-NOT:     ldp
; CHECK:         ldr
; CHECK:         add
; CHECK:         ret
  %a = load atomic i64, ptr %p acquire, align 8
  %q = getelementptr i8, ptr %p, i64 8
  %b = load i64, ptr %q, align 8
  %r = add i64 %a, %b
  ret i64 %r
}

;--- load: volatile → must NOT pair
define i64 @load_volatile_then_plain(ptr %p) {
; CHECK-LABEL: load_volatile_then_plain:
; CHECK:       // %bb.0:
; CHECK-NOT:     ldp
; CHECK:         ldr
; CHECK-NOT:     ldp
; CHECK:         ldr
; CHECK:         add
; CHECK:         ret
  %a = load volatile i64, ptr %p, align 8
  %q = getelementptr i8, ptr %p, i64 8
  %b = load i64, ptr %q, align 8
  %r = add i64 %a, %b
  ret i64 %r
}

;--- store: relaxed atomic first, then plain → STP
define void @store_relaxed_then_plain(ptr %p, i64 %a, i64 %b) {
; CHECK-LABEL: store_relaxed_then_plain:
; CHECK:       // %bb.0:
; CHECK-NEXT:    stp x1, x2, [x0]
; CHECK-NEXT:    ret
  store atomic i64 %a, ptr %p monotonic, align 8
  %q = getelementptr i8, ptr %p, i64 8
  store i64 %b, ptr %q, align 8
  ret void
}

;--- store: release atomic → must NOT pair (needs STLR)
define void @store_release_then_plain(ptr %p, i64 %a, i64 %b) {
; CHECK-LABEL: store_release_then_plain:
; CHECK:       // %bb.0:
; CHECK-NOT:     stp
; CHECK:         stlr
; CHECK-NOT:     stp
; CHECK:         str
; CHECK:         ret
  store atomic i64 %a, ptr %p release, align 8
  %q = getelementptr i8, ptr %p, i64 8
  store i64 %b, ptr %q, align 8
  ret void
}

;--- store: volatile → must NOT pair
define void @store_volatile_then_plain(ptr %p, i64 %a, i64 %b) {
; CHECK-LABEL: store_volatile_then_plain:
; CHECK:       // %bb.0:
; CHECK-NOT:     stp
; CHECK:         str
; CHECK-NOT:     stp
; CHECK:         str
; CHECK:         ret
  store volatile i64 %a, ptr %p, align 8
  %q = getelementptr i8, ptr %p, i64 8
  store i64 %b, ptr %q, align 8
  ret void
}

; With the flag off, relaxed atomics revert to 2x ldr (no pairing).
; RUN: llc -mtriple=aarch64 -verify-machineinstrs -aarch64-atomic-relaxed-pairing=0 < %s | FileCheck %s --check-prefix=DISABLED

; DISABLED-LABEL: load_relaxed_then_plain:
; DISABLED:       // %bb.0:
; DISABLED-NOT:     ldp
; DISABLED:         ldr
; DISABLED-NOT:     ldp
; DISABLED:         ldr
; DISABLED:         add
; DISABLED:         ret
