; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=aarch64 -verify-machineinstrs < %s | FileCheck %s --check-prefix=ENABLED
; RUN: llc -mtriple=aarch64 -verify-machineinstrs -aarch64-base-address-cse=0 < %s | FileCheck %s --check-prefix=NOBASECSE
;
; End-to-end tests for the AArch64 base-address CSE peephole (item 10 in
; AArch64MIPeepholeOpt).  When ISel materializes a per-access SUBXri/ADDXri
; base for far offsets it cannot fold into a single immediate, this pass
; coalesces sibling materializations sharing a common source so that the
; downstream load/store optimizer can form LDP/STP.
;
; The cases below use NEGATIVE far offsets, which (unlike positive far offsets)
; cannot be expressed as a single unsigned scaled immediate and therefore
; require base-address CSE to pair.  With the pass disabled (-aarch64-base-address-cse=0,
; NOBASECSE) the two accesses stay as separate sub+ldr/str with no LDP/STP.

define void @ldp_neg_far_offset_i32(ptr %p) {
; ENABLED-LABEL: ldp_neg_far_offset_i32:
; ENABLED:       // %bb.0:
; ENABLED-NEXT:    sub x[[TMP:[0-9]+]], x0, #400
; ENABLED-NEXT:    ldp w[[R0:[0-9]+]], w[[R1:[0-9]+]], [x[[TMP]]]
; ENABLED-NEXT:    str w[[R0]]
; ENABLED-NEXT:    str w[[R1]]
; ENABLED-NEXT:    ret
;
; NOBASECSE-LABEL: ldp_neg_far_offset_i32:
; NOBASECSE:       // %bb.0:
; NOBASECSE-NOT:     ldp
; NOBASECSE:        ret
  %gep0 = getelementptr i32, ptr %p, i64 -100
  %gep1 = getelementptr i32, ptr %p, i64 -99
  %v0 = load i32, ptr %gep0
  %v1 = load i32, ptr %gep1
  store volatile i32 %v0, ptr undef
  store volatile i32 %v1, ptr undef
  ret void
}

define void @ldp_neg_far_offset_i64(ptr %p) {
; ENABLED-LABEL: ldp_neg_far_offset_i64:
; ENABLED:       // %bb.0:
; ENABLED-NEXT:    sub x[[TMP:[0-9]+]], x0, #800
; ENABLED-NEXT:    ldp x[[R0:[0-9]+]], x[[R1:[0-9]+]], [x[[TMP]]]
; ENABLED-NEXT:    str x[[R0]]
; ENABLED-NEXT:    str x[[R1]]
; ENABLED-NEXT:    ret
;
; NOBASECSE-LABEL: ldp_neg_far_offset_i64:
; NOBASECSE:       // %bb.0:
; NOBASECSE-NOT:     ldp
; NOBASECSE:        ret
  %gep0 = getelementptr i64, ptr %p, i64 -100
  %gep1 = getelementptr i64, ptr %p, i64 -99
  %v0 = load i64, ptr %gep0
  %v1 = load i64, ptr %gep1
  store volatile i64 %v0, ptr undef
  store volatile i64 %v1, ptr undef
  ret void
}

define void @ldp_neg_far_offset_q(ptr %p) {
; ENABLED-LABEL: ldp_neg_far_offset_q:
; ENABLED:       // %bb.0:
; ENABLED-NEXT:    sub x[[TMP:[0-9]+]], x0, #1600
; ENABLED-NEXT:    ldp q0, q1, [x[[TMP]]]
; ENABLED-NEXT:    str q0, [x8]
; ENABLED-NEXT:    str q1, [x8]
; ENABLED-NEXT:    ret
;
; NOBASECSE-LABEL: ldp_neg_far_offset_q:
; NOBASECSE:       // %bb.0:
; NOBASECSE-NOT:     ldp
; NOBASECSE:        ret
  %gep0 = getelementptr <2 x i64>, ptr %p, i64 -100
  %gep1 = getelementptr <2 x i64>, ptr %p, i64 -99
  %v0 = load <2 x i64>, ptr %gep0
  %v1 = load <2 x i64>, ptr %gep1
  store volatile <2 x i64> %v0, ptr undef
  store volatile <2 x i64> %v1, ptr undef
  ret void
}

define void @ldp_neg_far_offset_large_i64(ptr %p) {
; Offset = -500 * 8 = -4000 bytes (fits in shift=0 SUBXri, <= 4095).
; ENABLED-LABEL: ldp_neg_far_offset_large_i64:
; ENABLED:       // %bb.0:
; ENABLED-NEXT:    sub x[[TMP:[0-9]+]], x0, #4000
; ENABLED-NEXT:    ldp x[[R0:[0-9]+]], x[[R1:[0-9]+]], [x[[TMP]]]
; ENABLED-NEXT:    str x[[R0]]
; ENABLED-NEXT:    str x[[R1]]
; ENABLED-NEXT:    ret
;
; NOBASECSE-LABEL: ldp_neg_far_offset_large_i64:
; NOBASECSE:       // %bb.0:
; NOBASECSE-NOT:     ldp
; NOBASECSE:        ret
  %gep0 = getelementptr i64, ptr %p, i64 -500
  %gep1 = getelementptr i64, ptr %p, i64 -499
  %v0 = load i64, ptr %gep0
  %v1 = load i64, ptr %gep1
  store volatile i64 %v0, ptr undef
  store volatile i64 %v1, ptr undef
  ret void
}

define void @stp_neg_far_offset_i32(ptr %p, i32 %v0, i32 %v1) {
; ENABLED-LABEL: stp_neg_far_offset_i32:
; ENABLED:       // %bb.0:
; ENABLED-NEXT:    sub x[[TMP:[0-9]+]], x0, #400
; ENABLED-NEXT:    stp w1, w2, [x[[TMP]]]
; ENABLED-NEXT:    ret
;
; NOBASECSE-LABEL: stp_neg_far_offset_i32:
; NOBASECSE:       // %bb.0:
; NOBASECSE-NOT:     stp
; NOBASECSE:        ret
  %gep0 = getelementptr i32, ptr %p, i64 -100
  %gep1 = getelementptr i32, ptr %p, i64 -99
  store i32 %v0, ptr %gep0
  store i32 %v1, ptr %gep1
  ret void
}

define void @stp_neg_far_offset_i64(ptr %p, i64 %v0, i64 %v1) {
; ENABLED-LABEL: stp_neg_far_offset_i64:
; ENABLED:       // %bb.0:
; ENABLED-NEXT:    sub x[[TMP:[0-9]+]], x0, #800
; ENABLED-NEXT:    stp x1, x2, [x[[TMP]]]
; ENABLED-NEXT:    ret
;
; NOBASECSE-LABEL: stp_neg_far_offset_i64:
; NOBASECSE:       // %bb.0:
; NOBASECSE-NOT:     stp
; NOBASECSE:        ret
  %gep0 = getelementptr i64, ptr %p, i64 -100
  %gep1 = getelementptr i64, ptr %p, i64 -99
  store i64 %v0, ptr %gep0
  store i64 %v1, ptr %gep1
  ret void
}

define void @stp_neg_far_offset_q(ptr %p, <2 x i64> %v0, <2 x i64> %v1) {
; ENABLED-LABEL: stp_neg_far_offset_q:
; ENABLED:       // %bb.0:
; ENABLED-NEXT:    sub x[[TMP:[0-9]+]], x0, #1600
; ENABLED-NEXT:    stp q0, q1, [x[[TMP]]]
; ENABLED-NEXT:    ret
;
; NOBASECSE-LABEL: stp_neg_far_offset_q:
; NOBASECSE:       // %bb.0:
; NOBASECSE-NOT:     stp
; NOBASECSE:        ret
  %gep0 = getelementptr <2 x i64>, ptr %p, i64 -100
  %gep1 = getelementptr <2 x i64>, ptr %p, i64 -99
  store <2 x i64> %v0, ptr %gep0
  store <2 x i64> %v1, ptr %gep1
  ret void
}

define void @stp_neg_far_offset_large_i64(ptr %p, i64 %v0, i64 %v1) {
; ENABLED-LABEL: stp_neg_far_offset_large_i64:
; ENABLED:       // %bb.0:
; ENABLED-NEXT:    sub x[[TMP:[0-9]+]], x0, #4000
; ENABLED-NEXT:    stp x1, x2, [x[[TMP]]]
; ENABLED-NEXT:    ret
;
; NOBASECSE-LABEL: stp_neg_far_offset_large_i64:
; NOBASECSE:       // %bb.0:
; NOBASECSE-NOT:     stp
; NOBASECSE:        ret
  %gep0 = getelementptr i64, ptr %p, i64 -500
  %gep1 = getelementptr i64, ptr %p, i64 -499
  store i64 %v0, ptr %gep0
  store i64 %v1, ptr %gep1
  ret void
}
