; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mcpu=hip12 -O2 -o - | FileCheck %s --check-prefix=FUSION
; RUN: llc < %s -mcpu=hip12 -mattr=-fuse-orr-eor -O2 -o - | FileCheck %s --check-prefix=NOFUSION

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128-Fn32"
target triple = "aarch64-unknown-linux-gnu"

; Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none) uwtable vscale_range(1,16)
define dso_local noundef <4 x i32> @test_vec_fuse_long(<4 x i32> noundef %a, <4 x i32> noundef %b, <4 x i32> noundef %mask, <4 x i32> noundef %c, <4 x i32> noundef %d, <4 x i32> noundef %e) #0 {
; FUSION-LABEL: test_vec_fuse_long:
; FUSION:       // %bb.0: // %entry
; FUSION-NEXT:    add v4.4s, v4.4s, v3.4s
; FUSION-NEXT:    orr v0.16b, v1.16b, v0.16b
; FUSION-NEXT:    eor v0.16b, v0.16b, v2.16b
; FUSION-NEXT:    mul v4.4s, v4.4s, v5.4s
; FUSION-NEXT:    shl v4.4s, v4.4s, #2
; FUSION-NEXT:    and v3.16b, v4.16b, v3.16b
; FUSION-NEXT:    add v0.4s, v3.4s, v0.4s
; FUSION-NEXT:    ret
;
; NOFUSION-LABEL: test_vec_fuse_long:
; NOFUSION:       // %bb.0: // %entry
; NOFUSION-NEXT:    orr v0.16b, v1.16b, v0.16b
; NOFUSION-NEXT:    add v1.4s, v4.4s, v3.4s
; NOFUSION-NEXT:    mul v1.4s, v1.4s, v5.4s
; NOFUSION-NEXT:    shl v1.4s, v1.4s, #2
; NOFUSION-NEXT:    and v1.16b, v1.16b, v3.16b
; NOFUSION-NEXT:    eor v0.16b, v0.16b, v2.16b
; NOFUSION-NEXT:    add v0.4s, v1.4s, v0.4s
; NOFUSION-NEXT:    ret
entry:
  %or.i = or <4 x i32> %b, %a
  %add.i7 = add <4 x i32> %d, %c
  %mul.i = mul <4 x i32> %add.i7, %e
  %vshl_n = shl <4 x i32> %mul.i, splat (i32 2)
  %and.i = and <4 x i32> %vshl_n, %c
  %xor.i = xor <4 x i32> %or.i, %mask
  %add.i = add <4 x i32> %and.i, %xor.i
  ret <4 x i32> %add.i
}

attributes #0 = { mustprogress nofree norecurse nosync nounwind willreturn memory(none) uwtable vscale_range(1,16) "frame-pointer"="non-leaf" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="hip12" "target-features"="+aes,+bf16,+brbe,+bti,+ccidx,+complxnum,+crc,+dit,+dotprod,+ete,+flagm,+fp-armv8,+fpac,+fullfp16,+hbc,+i8mm,+jsconv,+ls64,+lse,+mec,+neon,+nmi,+pauth,+perfmon,+predres,+ras,+rcpc,+rcpc-immo,+rcpc3,+rdm,+rme,+sb,+sha2,+sha3,+sm4,+spe,+spe-eef,+ssbs,+sve,+sve-aes,+sve-bitperm,+sve2,+sve2-sha3,+sve2-sm4,+trbe,+v8.1a,+v8.2a,+v8.3a,+v8.4a,+v8.5a,+v8.6a,+v8.7a,+v8a,+v9.1a,+v9.2a,+v9a,+wfxt,-fmv" }
