; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=aarch64 -verify-machineinstrs < %s | FileCheck %s --check-prefixes=CHECK,ENABLED
; RUN: llc -mtriple=aarch64 -verify-machineinstrs -aarch64-ldp-stp-base-adjust=0 < %s | FileCheck %s --check-prefixes=CHECK,DISABLED

define void @ldp_far_offset_i32(ptr %p) {
; ENABLED-LABEL: ldp_far_offset_i32:
; ENABLED:       // %bb.0:
; ENABLED-NEXT:    add x[[TMP:[0-9]+]], x0, #400
; ENABLED-NEXT:    ldp w[[R0:[0-9]+]], w[[R1:[0-9]+]], [x[[TMP]]]
; ENABLED-NEXT:    str w[[R0]]
; ENABLED-NEXT:    str w[[R1]]
; ENABLED-NEXT:    ret
;
; DISABLED-LABEL: ldp_far_offset_i32:
; DISABLED:       // %bb.0:
; DISABLED-NOT:     ldp w
; DISABLED-NOT:     ldp x
; DISABLED:        ret
  %gep0 = getelementptr i32, ptr %p, i64 100
  %gep1 = getelementptr i32, ptr %p, i64 101
  %v0 = load i32, ptr %gep0
  %v1 = load i32, ptr %gep1
  store volatile i32 %v0, ptr undef
  store volatile i32 %v1, ptr undef
  ret void
}

define void @ldp_far_offset_i64(ptr %p) {
; ENABLED-LABEL: ldp_far_offset_i64:
; ENABLED:       // %bb.0:
; ENABLED-NEXT:    add x[[TMP:[0-9]+]], x0, #800
; ENABLED-NEXT:    ldp x[[R0:[0-9]+]], x[[R1:[0-9]+]], [x[[TMP]]]
; ENABLED-NEXT:    str x[[R0]]
; ENABLED-NEXT:    str x[[R1]]
; ENABLED-NEXT:    ret
;
; DISABLED-LABEL: ldp_far_offset_i64:
; DISABLED:       // %bb.0:
; DISABLED-NOT:     ldp w
; DISABLED-NOT:     ldp x
; DISABLED:        ret
  %gep0 = getelementptr i64, ptr %p, i64 100
  %gep1 = getelementptr i64, ptr %p, i64 101
  %v0 = load i64, ptr %gep0
  %v1 = load i64, ptr %gep1
  store volatile i64 %v0, ptr undef
  store volatile i64 %v1, ptr undef
  ret void
}

define void @ldp_near_offset(ptr %p) {
; Near offsets within LDP range — always pair regardless of the option.
; CHECK-LABEL: ldp_near_offset:
; CHECK:       // %bb.0:
; CHECK-NOT:     add
; CHECK:        ldp w{{[0-9]+}}, w{{[0-9]+}}, [x0, #40]
; CHECK:        ret
  %gep0 = getelementptr i32, ptr %p, i64 10
  %gep1 = getelementptr i32, ptr %p, i64 11
  %v0 = load i32, ptr %gep0
  %v1 = load i32, ptr %gep1
  store volatile i32 %v0, ptr undef
  store volatile i32 %v1, ptr undef
  ret void
}

define void @ldp_far_offset_interleaved(ptr %p, ptr %q) {
; Intervening load from a different base between two far-offset loads.
; ENABLED-LABEL: ldp_far_offset_interleaved:
; ENABLED:       add x[[TMP:[0-9]+]], x0, #400
; ENABLED:       ldp w{{[0-9]+}}, w{{[0-9]+}}, [x[[TMP]]]
;
; DISABLED-LABEL: ldp_far_offset_interleaved:
; DISABLED-NOT:   ldp w
; DISABLED-NOT:   ldp x
; DISABLED:       ret
  %gep0 = getelementptr i32, ptr %p, i64 100
  %gep1 = getelementptr i32, ptr %p, i64 101
  %v0 = load i32, ptr %gep0
  %v2 = load volatile i32, ptr %q
  %v1 = load i32, ptr %gep1
  store volatile i32 %v0, ptr undef
  store volatile i32 %v1, ptr undef
  ret void
}

define void @ldp_far_offset_already_4k_aligned_i32(ptr %p) {
; Offset = 1024 elements * 4 bytes = 4096 bytes = 0x1000
; The ADDXri encodes as #1, LSL #12 which equals 4096.
; ENABLED-LABEL: ldp_far_offset_already_4k_aligned_i32:
; ENABLED:       add x[[TMP:[0-9]+]], x0, #1, lsl #12
; ENABLED:       ldp w{{[0-9]+}}, w{{[0-9]+}}, [x[[TMP]]]
;
; DISABLED-LABEL: ldp_far_offset_already_4k_aligned_i32:
; DISABLED-NOT:   ldp w
; DISABLED-NOT:   ldp x
; DISABLED:       ret
  %gep0 = getelementptr i32, ptr %p, i64 1024
  %gep1 = getelementptr i32, ptr %p, i64 1025
  %v0 = load i32, ptr %gep0
  %v1 = load i32, ptr %gep1
  store volatile i32 %v0, ptr undef
  store volatile i32 %v1, ptr undef
  ret void
}

define void @ldp_far_offset_large_i64(ptr %p) {
; Offset = 500 * 8 = 4000 bytes (fits in shift=0, <= 4095)
; ENABLED-LABEL: ldp_far_offset_large_i64:
; ENABLED:       add x[[TMP:[0-9]+]], x0, #4000
; ENABLED:       ldp x{{[0-9]+}}, x{{[0-9]+}}, [x[[TMP]]]
;
; DISABLED-LABEL: ldp_far_offset_large_i64:
; DISABLED-NOT:   ldp w
; DISABLED-NOT:   ldp x
; DISABLED:       ret
  %gep0 = getelementptr i64, ptr %p, i64 500
  %gep1 = getelementptr i64, ptr %p, i64 501
  %v0 = load i64, ptr %gep0
  %v1 = load i64, ptr %gep1
  store volatile i64 %v0, ptr undef
  store volatile i64 %v1, ptr undef
  ret void
}

define void @ldp_far_offset_q(ptr %p) {
; ENABLED-LABEL: ldp_far_offset_q:
; ENABLED:       // %bb.0:
; ENABLED-NEXT:    add x[[TMP:[0-9]+]], x0, #1600
; ENABLED-NEXT:    ldp q0, q1, [x[[TMP]]]
; ENABLED-NEXT:    str q0, [x8]
; ENABLED-NEXT:    str q1, [x8]
; ENABLED-NEXT:    ret
;
; DISABLED-LABEL: ldp_far_offset_q:
; DISABLED:       // %bb.0:
; DISABLED-NEXT:    ldr q0, [x0, #1600]
; DISABLED-NEXT:    ldr q1, [x0, #1616]
; DISABLED-NEXT:    str q0, [x8]
; DISABLED-NEXT:    str q1, [x8]
; DISABLED-NEXT:    ret
  %gep0 = getelementptr <2 x i64>, ptr %p, i64 100
  %gep1 = getelementptr <2 x i64>, ptr %p, i64 101
  %v0 = load <2 x i64>, ptr %gep0
  %v1 = load <2 x i64>, ptr %gep1
  store volatile <2 x i64> %v0, ptr undef
  store volatile <2 x i64> %v1, ptr undef
  ret void
}

define void @ldp_far_offset_q_aligned_4k(ptr %p) {
; Offset = 256 * 16 = 4096 bytes = 0x1000
; The ADDXri encodes as #1, LSL #12 which equals 4096.
; ENABLED-LABEL: ldp_far_offset_q_aligned_4k:
; ENABLED:       // %bb.0:
; ENABLED-NEXT:    add x[[TMP:[0-9]+]], x0, #1, lsl #12
; ENABLED-NEXT:    ldp q0, q1, [x[[TMP]]]
; ENABLED-NEXT:    str q0, [x8]
; ENABLED-NEXT:    str q1, [x8]
; ENABLED-NEXT:    ret
;
; DISABLED-LABEL: ldp_far_offset_q_aligned_4k:
; DISABLED:       // %bb.0:
; DISABLED-NEXT:    ldr q0, [x0, #4096]
; DISABLED-NEXT:    ldr q1, [x0, #4112]
; DISABLED-NEXT:    str q0, [x8]
; DISABLED-NEXT:    str q1, [x8]
; DISABLED-NEXT:    ret
  %gep0 = getelementptr <2 x i64>, ptr %p, i64 256
  %gep1 = getelementptr <2 x i64>, ptr %p, i64 257
  %v0 = load <2 x i64>, ptr %gep0
  %v1 = load <2 x i64>, ptr %gep1
  store volatile <2 x i64> %v0, ptr undef
  store volatile <2 x i64> %v1, ptr undef
  ret void
}
