; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -mtriple=aarch64-linux-gnu -mcpu=tsv110 -O2 -enable-malloc-merge=true < %s | FileCheck %s

@g = dso_local global ptr null, align 8
@.str.scanf = private unnamed_addr constant [3 x i8] c"%d\00", align 1
@.str.printf = private unnamed_addr constant [3 x i8] c"%p\00", align 1

declare noalias ptr @malloc(i64) #0
declare void @free(ptr) #0
declare i32 @__isoc99_scanf(ptr, ...) #0
declare i32 @printf(ptr, ...) #0
declare void @use(ptr) #0

define dso_local noundef i32 @merge_single_bb() #0 {
; CHECK-LABEL: merge_single_bb:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; CHECK-NEXT:    mov w0, #49152 // =0xc000
; CHECK-NEXT:    bl malloc
; CHECK-NEXT:    bl free
; CHECK-NEXT:    mov w0, wzr
; CHECK-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; CHECK-NEXT:    ret
entry:
  %call = call noalias ptr @malloc(i64 noundef 16384)
  %call3 = call noalias ptr @malloc(i64 noundef 32768)
  call void @free(ptr noundef %call3)
  call void @free(ptr noundef %call)
  ret i32 0
}

define dso_local noundef i32 @merge_branch() #0 {
; CHECK-LABEL: merge_branch:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    str x30, [sp, #-64]! // 8-byte Folded Spill
; CHECK-NEXT:    adrp x0, .L.str.scanf
; CHECK-NEXT:    add x1, sp, #12
; CHECK-NEXT:    stp x24, x23, [sp, #16] // 16-byte Folded Spill
; CHECK-NEXT:    add x0, x0, :lo12:.L.str.scanf
; CHECK-NEXT:    stp x22, x21, [sp, #32] // 16-byte Folded Spill
; CHECK-NEXT:    stp x20, x19, [sp, #48] // 16-byte Folded Spill
; CHECK-NEXT:    str wzr, [sp, #12]
; CHECK-NEXT:    bl __isoc99_scanf
; CHECK-NEXT:    ldr w20, [sp, #12]
; CHECK-NEXT:    mov w0, #16384 // =0x4000
; CHECK-NEXT:    movk w0, #1, lsl #16
; CHECK-NEXT:    bl malloc
; CHECK-NEXT:    mov x19, x0
; CHECK-NEXT:    add x23, x0, #8, lsl #12 // =32768
; CHECK-NEXT:    cbz w20, .LBB1_2
; CHECK-NEXT:  // %bb.1: // %if.then
; CHECK-NEXT:    mov w0, #65536 // =0x10000
; CHECK-NEXT:    bl malloc
; CHECK-NEXT:    mov x22, x0
; CHECK-NEXT:    mov w0, #32768 // =0x8000
; CHECK-NEXT:    mov w24, #32768 // =0x8000
; CHECK-NEXT:    bl malloc
; CHECK-NEXT:    mov x20, x0
; CHECK-NEXT:    mov w0, #32768 // =0x8000
; CHECK-NEXT:    bl malloc
; CHECK-NEXT:    mov x8, #55050 // =0xd70a
; CHECK-NEXT:    mov x21, x0
; CHECK-NEXT:    movk x8, #28835, lsl #16
; CHECK-NEXT:    movk x8, #43581, lsl #32
; CHECK-NEXT:    movk x8, #16448, lsl #48
; CHECK-NEXT:    str x8, [x22]
; CHECK-NEXT:    mov x8, #7864 // =0x1eb8
; CHECK-NEXT:    movk x8, #60293, lsl #16
; CHECK-NEXT:    movk x8, #14417, lsl #32
; CHECK-NEXT:    movk x8, #16454, lsl #48
; CHECK-NEXT:    str x8, [x22, x24]
; CHECK-NEXT:    mov x8, #7378697629483820646 // =0x6666666666666666
; CHECK-NEXT:    movk x8, #50790, lsl #32
; CHECK-NEXT:    movk x8, #16459, lsl #48
; CHECK-NEXT:    str x8, [x20]
; CHECK-NEXT:    mov x8, #55050 // =0xd70a
; CHECK-NEXT:    movk x8, #28835, lsl #16
; CHECK-NEXT:    movk x8, #43581, lsl #32
; CHECK-NEXT:    movk x8, #16464, lsl #48
; CHECK-NEXT:    str x8, [x0]
; CHECK-NEXT:    mov x0, x22
; CHECK-NEXT:    bl free
; CHECK-NEXT:    b .LBB1_3
; CHECK-NEXT:  .LBB1_2: // %if.else
; CHECK-NEXT:    mov w0, #98304 // =0x18000
; CHECK-NEXT:    bl malloc
; CHECK-NEXT:    mov x20, x0
; CHECK-NEXT:    mov w0, #32768 // =0x8000
; CHECK-NEXT:    bl malloc
; CHECK-NEXT:    mov x8, #70368744177664 // =0x400000000000
; CHECK-NEXT:    mov x21, x0
; CHECK-NEXT:    movk x8, #16467, lsl #48
; CHECK-NEXT:    str x8, [x20]
; CHECK-NEXT:    mov x8, #7864 // =0x1eb8
; CHECK-NEXT:    movk x8, #60293, lsl #16
; CHECK-NEXT:    movk x8, #14417, lsl #32
; CHECK-NEXT:    movk x8, #16470, lsl #48
; CHECK-NEXT:    str x8, [x0]
; CHECK-NEXT:  .LBB1_3: // %if.end
; CHECK-NEXT:    mov x0, x20
; CHECK-NEXT:    bl free
; CHECK-NEXT:    mov x0, x21
; CHECK-NEXT:    bl free
; CHECK-NEXT:    mov w8, #123 // =0x7b
; CHECK-NEXT:    mov x0, x19
; CHECK-NEXT:    str w8, [x23]
; CHECK-NEXT:    mov x8, #34079 // =0x851f
; CHECK-NEXT:    movk x8, #20971, lsl #16
; CHECK-NEXT:    movk x8, #7864, lsl #32
; CHECK-NEXT:    movk x8, #16393, lsl #48
; CHECK-NEXT:    str x8, [x19]
; CHECK-NEXT:    bl free
; CHECK-NEXT:    ldp x20, x19, [sp, #48] // 16-byte Folded Reload
; CHECK-NEXT:    ldp x22, x21, [sp, #32] // 16-byte Folded Reload
; CHECK-NEXT:    ldp x24, x23, [sp, #16] // 16-byte Folded Reload
; CHECK-NEXT:    mov w0, wzr
; CHECK-NEXT:    ldr x30, [sp], #64 // 8-byte Folded Reload
; CHECK-NEXT:    ret
entry:
  %tmp = alloca i32, align 4
  store i32 0, ptr %tmp, align 4
  %call = call i32 (ptr, ...) @__isoc99_scanf(ptr noundef nonnull @.str.scanf,
                                              ptr noundef nonnull %tmp)
  %0 = load i32, ptr %tmp, align 4
  %cmp.not = icmp eq i32 %0, 0
  %call1 = call noalias ptr @malloc(i64 noundef 32768)
  %call4 = call noalias ptr @malloc(i64 noundef 16384)
  %call7 = call noalias ptr @malloc(i64 noundef 32768)
  br i1 %cmp.not, label %if.else, label %if.then

if.then:
  %call10 = call noalias ptr @malloc(i64 noundef 32768)
  %call13 = call noalias ptr @malloc(i64 noundef 32768)
  %call16 = call noalias ptr @malloc(i64 noundef 32768)
  %call19 = call noalias ptr @malloc(i64 noundef 32768)
  store double 3.333000e+01, ptr %call10, align 8
  store double 4.444000e+01, ptr %call13, align 8
  store double 5.555000e+01, ptr %call16, align 8
  store double 6.666000e+01, ptr %call19, align 8
  call void @free(ptr noundef %call10)
  call void @free(ptr noundef %call13)
  call void @free(ptr noundef %call16)
  call void @free(ptr noundef %call19)
  br label %if.end

if.else:
  %call27 = call noalias ptr @malloc(i64 noundef 98304)
  %call31 = call noalias ptr @malloc(i64 noundef 32768)
  store double 7.700000e+01, ptr %call27, align 8
  store double 0x40563851EB851EB8, ptr %call31, align 8
  call void @free(ptr noundef %call27)
  call void @free(ptr noundef %call31)
  br label %if.end

if.end:
  store i32 123, ptr %call4, align 4
  store double 3.140000e+00, ptr %call1, align 8
  call void @free(ptr noundef %call7)
  call void @free(ptr noundef %call1)
  call void @free(ptr noundef %call4)
  ret i32 0
}

define dso_local noundef i32 @merge_double_pointer() #0 {
; CHECK-LABEL: merge_double_pointer:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    str x30, [sp, #-16]! // 8-byte Folded Spill
; CHECK-NEXT:    mov w0, #32880 // =0x8070
; CHECK-NEXT:    movk w0, #1, lsl #16
; CHECK-NEXT:    bl malloc
; CHECK-NEXT:    mov w8, #66 // =0x42
; CHECK-NEXT:    mov x9, x0
; CHECK-NEXT:    mov x10, #55050 // =0xd70a
; CHECK-NEXT:    add x11, x0, #16, lsl #12 // =65536
; CHECK-NEXT:    strb w8, [x9, #80]!
; CHECK-NEXT:    mov w8, #77 // =0x4d
; CHECK-NEXT:    str x9, [x0]
; CHECK-NEXT:    mov x9, x0
; CHECK-NEXT:    movk x10, #28835, lsl #16
; CHECK-NEXT:    movk x10, #43581, lsl #32
; CHECK-NEXT:    movk x10, #16448, lsl #48
; CHECK-NEXT:    strb w8, [x9, #96]!
; CHECK-NEXT:    mov w8, #32880 // =0x8070
; CHECK-NEXT:    str x9, [x0, #16]
; CHECK-NEXT:    mov x9, x0
; CHECK-NEXT:    add x8, x0, x8
; CHECK-NEXT:    str x10, [x9, #112]!
; CHECK-NEXT:    add x10, x11, #112
; CHECK-NEXT:    str x8, [x0, #48]
; CHECK-NEXT:    str x9, [x0, #32]
; CHECK-NEXT:    mov x9, #7864 // =0x1eb8
; CHECK-NEXT:    movk x9, #60293, lsl #16
; CHECK-NEXT:    str x10, [x0, #64]
; CHECK-NEXT:    movk x9, #14417, lsl #32
; CHECK-NEXT:    movk x9, #16454, lsl #48
; CHECK-NEXT:    str x9, [x8]
; CHECK-NEXT:    mov x8, #7378697629483820646 // =0x6666666666666666
; CHECK-NEXT:    movk x8, #50790, lsl #32
; CHECK-NEXT:    movk x8, #16459, lsl #48
; CHECK-NEXT:    str x8, [x10]
; CHECK-NEXT:    bl free
; CHECK-NEXT:    mov w0, wzr
; CHECK-NEXT:    ldr x30, [sp], #16 // 8-byte Folded Reload
; CHECK-NEXT:    ret
entry:
  %call = call noalias ptr @malloc(i64 noundef 8)
  %call1 = call noalias ptr @malloc(i64 noundef 8)
  %call2 = call noalias ptr @malloc(i64 noundef 8)
  %call3 = call noalias ptr @malloc(i64 noundef 8)
  %call4 = call noalias ptr @malloc(i64 noundef 8)
  %call5 = call noalias ptr @malloc(i64 noundef 1)
  store ptr %call5, ptr %call, align 8
  %call6 = call noalias ptr @malloc(i64 noundef 2)
  store ptr %call6, ptr %call1, align 8
  %call8 = call noalias ptr @malloc(i64 noundef 32768)
  store ptr %call8, ptr %call2, align 8
  %call12 = call noalias ptr @malloc(i64 noundef 32768)
  store ptr %call12, ptr %call3, align 8
  %call16 = call noalias ptr @malloc(i64 noundef 32768)
  store ptr %call16, ptr %call4, align 8
  %0 = load ptr, ptr %call2, align 8
  store double 3.333000e+01, ptr %0, align 8
  %1 = load ptr, ptr %call3, align 8
  store double 4.444000e+01, ptr %1, align 8
  %2 = load ptr, ptr %call4, align 8
  store double 5.555000e+01, ptr %2, align 8
  %3 = load ptr, ptr %call, align 8
  store i8 66, ptr %3, align 1
  %4 = load ptr, ptr %call1, align 8
  store i8 77, ptr %4, align 1
  %5 = load ptr, ptr %call2, align 8
  call void @free(ptr noundef %5)
  %6 = load ptr, ptr %call3, align 8
  call void @free(ptr noundef %6)
  %7 = load ptr, ptr %call4, align 8
  call void @free(ptr noundef %7)
  %8 = load ptr, ptr %call, align 8
  call void @free(ptr noundef %8)
  %9 = load ptr, ptr %call1, align 8
  call void @free(ptr noundef %9)
  call void @free(ptr noundef %call2)
  call void @free(ptr noundef %call3)
  call void @free(ptr noundef %call4)
  call void @free(ptr noundef %call)
  call void @free(ptr noundef %call1)
  ret i32 0
}

define dso_local noundef i32 @no_merge_escape() #0 {
; CHECK-LABEL: no_merge_escape:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    stp x30, x21, [sp, #-32]! // 16-byte Folded Spill
; CHECK-NEXT:    mov w0, #16384 // =0x4000
; CHECK-NEXT:    stp x20, x19, [sp, #16] // 16-byte Folded Spill
; CHECK-NEXT:    bl malloc
; CHECK-NEXT:    mov x19, x0
; CHECK-NEXT:    mov w0, #32768 // =0x8000
; CHECK-NEXT:    bl malloc
; CHECK-NEXT:    mov x20, x0
; CHECK-NEXT:    mov w0, #32768 // =0x8000
; CHECK-NEXT:    bl malloc
; CHECK-NEXT:    adrp x21, g
; CHECK-NEXT:    mov x1, x19
; CHECK-NEXT:    str x0, [x21, :lo12:g]
; CHECK-NEXT:    adrp x0, .L.str.printf
; CHECK-NEXT:    add x0, x0, :lo12:.L.str.printf
; CHECK-NEXT:    bl printf
; CHECK-NEXT:    ldr x0, [x21, :lo12:g]
; CHECK-NEXT:    bl free
; CHECK-NEXT:    mov x0, x20
; CHECK-NEXT:    bl free
; CHECK-NEXT:    mov x0, x19
; CHECK-NEXT:    bl free
; CHECK-NEXT:    ldp x20, x19, [sp, #16] // 16-byte Folded Reload
; CHECK-NEXT:    mov w0, wzr
; CHECK-NEXT:    ldp x30, x21, [sp], #32 // 16-byte Folded Reload
; CHECK-NEXT:    ret
entry:
  %call = call noalias ptr @malloc(i64 noundef 16384)
  %call3 = call noalias ptr @malloc(i64 noundef 32768)
  %call6 = call noalias ptr @malloc(i64 noundef 32768)
  store ptr %call6, ptr @g, align 8
  %call7 = call i32 (ptr, ...) @printf(ptr noundef nonnull @.str.printf,
                                       ptr noundef %call)
  %0 = load ptr, ptr @g, align 8
  call void @free(ptr noundef %0)
  call void @free(ptr noundef %call3)
  call void @free(ptr noundef %call)
  ret i32 0
}

define dso_local void @no_merge_free_not_postdom(i1 %c) #0 {
; CHECK-LABEL: no_merge_free_not_postdom:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    stp x30, x21, [sp, #-32]! // 16-byte Folded Spill
; CHECK-NEXT:    mov w21, w0
; CHECK-NEXT:    mov w0, #16384 // =0x4000
; CHECK-NEXT:    stp x20, x19, [sp, #16] // 16-byte Folded Spill
; CHECK-NEXT:    bl malloc
; CHECK-NEXT:    mov x19, x0
; CHECK-NEXT:    mov w0, #32768 // =0x8000
; CHECK-NEXT:    bl malloc
; CHECK-NEXT:    mov x20, x0
; CHECK-NEXT:    tbz w21, #0, .LBB4_2
; CHECK-NEXT:  // %bb.1: // %free.call
; CHECK-NEXT:    mov x0, x19
; CHECK-NEXT:    bl free
; CHECK-NEXT:  .LBB4_2: // %end
; CHECK-NEXT:    mov x0, x20
; CHECK-NEXT:    bl free
; CHECK-NEXT:    ldp x20, x19, [sp, #16] // 16-byte Folded Reload
; CHECK-NEXT:    ldp x30, x21, [sp], #32 // 16-byte Folded Reload
; CHECK-NEXT:    ret
entry:
  %call = call noalias ptr @malloc(i64 noundef 16384)
  %call1 = call noalias ptr @malloc(i64 noundef 32768)
  br i1 %c, label %free.call, label %end

free.call:
  call void @free(ptr noundef %call)
  br label %end

end:
  call void @free(ptr noundef %call1)
  ret void
}

define dso_local void @no_merge_malloc_not_dom(i1 %c) #0 {
; CHECK-LABEL: no_merge_malloc_not_dom:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    str x30, [sp, #-32]! // 8-byte Folded Spill
; CHECK-NEXT:    stp x20, x19, [sp, #16] // 16-byte Folded Spill
; CHECK-NEXT:    mov w20, w0
; CHECK-NEXT:    mov w0, #16384 // =0x4000
; CHECK-NEXT:    bl malloc
; CHECK-NEXT:    mov x19, x0
; CHECK-NEXT:    tbz w20, #0, .LBB5_2
; CHECK-NEXT:  // %bb.1: // %if.then
; CHECK-NEXT:    mov w0, #32768 // =0x8000
; CHECK-NEXT:    bl malloc
; CHECK-NEXT:    b .LBB5_3
; CHECK-NEXT:  .LBB5_2:
; CHECK-NEXT:    mov x0, xzr
; CHECK-NEXT:  .LBB5_3: // %if.end
; CHECK-NEXT:    bl free
; CHECK-NEXT:    mov x0, x19
; CHECK-NEXT:    bl free
; CHECK-NEXT:    ldp x20, x19, [sp, #16] // 16-byte Folded Reload
; CHECK-NEXT:    ldr x30, [sp], #32 // 8-byte Folded Reload
; CHECK-NEXT:    ret
entry:
  %call = call noalias ptr @malloc(i64 noundef 16384)
  br i1 %c, label %if.then, label %if.else

if.then:
  %call1 = call noalias ptr @malloc(i64 noundef 32768)
  br label %if.end

if.else:
  br label %if.end

if.end:
  %p = phi ptr [ %call1, %if.then ], [ null, %if.else ]
  call void @free(ptr noundef %p)
  call void @free(ptr noundef %call)
  ret void
}



attributes #0 = { nounwind }
