; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
target triple = "aarch64-unknown-linux-gnu"
; RUN: llc -mtriple=aarch64-linux-gnu -mattr=+sve -mcpu=hip12 -mattr=+use-experimental-zeroing-pseudos < %s | FileCheck %s --check-prefix=TRANSFORM
; RUN: llc -mtriple=aarch64-linux-gnu -mattr=+sve -mattr=+use-experimental-zeroing-pseudos < %s | FileCheck %s --check-prefix=NOTRANSFORM


define dso_local <vscale x 16 x i8> @test_mad_s8(<vscale x 16 x i1> %pg, <vscale x 16 x i8> %e) {
; TRANSFORM-LABEL: test_mad_s8:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    mad z1.b, p0/m, z0.b, z0.b
; TRANSFORM-NEXT:    mad z0.b, p0/m, z0.b, z1.b
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_mad_s8:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    mad z1.b, p0/m, z0.b, z0.b
; NOTRANSFORM-NEXT:    mad z0.b, p0/m, z0.b, z1.b
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 16 x i8> @llvm.aarch64.sve.mad.nxv16i8(<vscale x 16 x i1> %pg, <vscale x 16 x i8> %e, <vscale x 16 x i8> %e, <vscale x 16 x i8> %e)
  %2 = tail call <vscale x 16 x i8> @llvm.aarch64.sve.mad.nxv16i8(<vscale x 16 x i1> %pg, <vscale x 16 x i8> %e, <vscale x 16 x i8> %e, <vscale x 16 x i8> %1)
  ret <vscale x 16 x i8> %2
}

define dso_local <vscale x 8 x i16> @test_mad_s16(<vscale x 8 x i1> %pg, <vscale x 8 x i16> %e) {
; TRANSFORM-LABEL: test_mad_s16:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    mad z1.h, p0/m, z0.h, z0.h
; TRANSFORM-NEXT:    mad z0.h, p0/m, z0.h, z1.h
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_mad_s16:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    mad z1.h, p0/m, z0.h, z0.h
; NOTRANSFORM-NEXT:    mad z0.h, p0/m, z0.h, z1.h
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 8 x i16> @llvm.aarch64.sve.mad.nxv8i16(<vscale x 8 x i1> %pg, <vscale x 8 x i16> %e, <vscale x 8 x i16> %e, <vscale x 8 x i16> %e)
  %2 = tail call <vscale x 8 x i16> @llvm.aarch64.sve.mad.nxv8i16(<vscale x 8 x i1> %pg, <vscale x 8 x i16> %e, <vscale x 8 x i16> %e, <vscale x 8 x i16> %1)
  ret <vscale x 8 x i16> %2
}

declare <vscale x 16 x i8> @llvm.aarch64.sve.mad.nxv16i8(<vscale x 16 x i1>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>)
declare <vscale x 8 x i16> @llvm.aarch64.sve.mad.nxv8i16(<vscale x 8 x i1>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>)
