; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
target triple = "aarch64-unknown-linux-gnu"
; RUN: llc -mtriple=aarch64-linux-gnu -mattr=+sve,+sve2 -mcpu=hip12 -mattr=+use-experimental-zeroing-pseudos < %s | FileCheck %s --check-prefix=TRANSFORM
; RUN: llc -mtriple=aarch64-linux-gnu -mattr=+sve,+sve2 -mattr=+use-experimental-zeroing-pseudos < %s | FileCheck %s --check-prefix=NOTRANSFORM

;; ============================================================================
;; Group A: 4-op predicated FMA (PredIdx=1, DOPIdx=2, SrcIdx=3, Src2Idx=4)
;; ============================================================================

define dso_local <vscale x 16 x i8> @test_mad_s8(<vscale x 16 x i1> %pg, <vscale x 16 x i8> %e) {
; TRANSFORM-LABEL: test_mad_s8:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    mad z1.b, p0/m, z0.b, z0.b
; TRANSFORM-NEXT:    mad z0.b, p0/m, z0.b, z1.b
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_mad_s8:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    mad z1.b, p0/m, z0.b, z0.b
; NOTRANSFORM-NEXT:    mad z0.b, p0/m, z0.b, z1.b
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 16 x i8> @llvm.aarch64.sve.mad.nxv16i8(<vscale x 16 x i1> %pg, <vscale x 16 x i8> %e, <vscale x 16 x i8> %e, <vscale x 16 x i8> %e)
  %2 = tail call <vscale x 16 x i8> @llvm.aarch64.sve.mad.nxv16i8(<vscale x 16 x i1> %pg, <vscale x 16 x i8> %e, <vscale x 16 x i8> %e, <vscale x 16 x i8> %1)
  ret <vscale x 16 x i8> %2
}

define dso_local <vscale x 8 x i16> @test_mad_s16(<vscale x 8 x i1> %pg, <vscale x 8 x i16> %e) {
; TRANSFORM-LABEL: test_mad_s16:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    mad z1.h, p0/m, z0.h, z0.h
; TRANSFORM-NEXT:    mad z0.h, p0/m, z0.h, z1.h
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_mad_s16:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    mad z1.h, p0/m, z0.h, z0.h
; NOTRANSFORM-NEXT:    mad z0.h, p0/m, z0.h, z1.h
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 8 x i16> @llvm.aarch64.sve.mad.nxv8i16(<vscale x 8 x i1> %pg, <vscale x 8 x i16> %e, <vscale x 8 x i16> %e, <vscale x 8 x i16> %e)
  %2 = tail call <vscale x 8 x i16> @llvm.aarch64.sve.mad.nxv8i16(<vscale x 8 x i1> %pg, <vscale x 8 x i16> %e, <vscale x 8 x i16> %e, <vscale x 8 x i16> %1)
  ret <vscale x 8 x i16> %2
}

define dso_local <vscale x 4 x i32> @test_mad_s32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %e) {
; TRANSFORM-LABEL: test_mad_s32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    mad z1.s, p0/m, z0.s, z0.s
; TRANSFORM-NEXT:    mad z0.s, p0/m, z0.s, z1.s
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_mad_s32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    mad z1.s, p0/m, z0.s, z0.s
; NOTRANSFORM-NEXT:    mad z0.s, p0/m, z0.s, z1.s
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.mad.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %e, <vscale x 4 x i32> %e, <vscale x 4 x i32> %e)
  %2 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.mad.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %e, <vscale x 4 x i32> %e, <vscale x 4 x i32> %1)
  ret <vscale x 4 x i32> %2
}

define dso_local <vscale x 2 x i64> @test_mad_s64(<vscale x 2 x i1> %pg, <vscale x 2 x i64> %e) {
; TRANSFORM-LABEL: test_mad_s64:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    mad z1.d, p0/m, z0.d, z0.d
; TRANSFORM-NEXT:    mad z0.d, p0/m, z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_mad_s64:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    mad z1.d, p0/m, z0.d, z0.d
; NOTRANSFORM-NEXT:    mad z0.d, p0/m, z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.mad.nxv2i64(<vscale x 2 x i1> %pg, <vscale x 2 x i64> %e, <vscale x 2 x i64> %e, <vscale x 2 x i64> %e)
  %2 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.mad.nxv2i64(<vscale x 2 x i1> %pg, <vscale x 2 x i64> %e, <vscale x 2 x i64> %e, <vscale x 2 x i64> %1)
  ret <vscale x 2 x i64> %2
}

define dso_local <vscale x 16 x i8> @test_mla_s8(<vscale x 16 x i1> %pg, <vscale x 16 x i8> %a, <vscale x 16 x i8> %b) {
; TRANSFORM-LABEL: test_mla_s8:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z2, z0
; TRANSFORM-NEXT:    mla z2.b, p0/m, z0.b, z1.b
; TRANSFORM-NEXT:    mla z2.b, p0/m, z0.b, z1.b
; TRANSFORM-NEXT:    mov z0.d, z2.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_mla_s8:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z2.d, z0.d
; NOTRANSFORM-NEXT:    mla z2.b, p0/m, z0.b, z1.b
; NOTRANSFORM-NEXT:    mla z2.b, p0/m, z0.b, z1.b
; NOTRANSFORM-NEXT:    mov z0.d, z2.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 16 x i8> @llvm.aarch64.sve.mla.nxv16i8(<vscale x 16 x i1> %pg, <vscale x 16 x i8> %a, <vscale x 16 x i8> %a, <vscale x 16 x i8> %b)
  %2 = tail call <vscale x 16 x i8> @llvm.aarch64.sve.mla.nxv16i8(<vscale x 16 x i1> %pg, <vscale x 16 x i8> %1, <vscale x 16 x i8> %a, <vscale x 16 x i8> %b)
  ret <vscale x 16 x i8> %2
}

define dso_local <vscale x 16 x i8> @test_mls_s8(<vscale x 16 x i1> %pg, <vscale x 16 x i8> %a, <vscale x 16 x i8> %b) {
; TRANSFORM-LABEL: test_mls_s8:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z2, z0
; TRANSFORM-NEXT:    mls z2.b, p0/m, z0.b, z1.b
; TRANSFORM-NEXT:    mls z2.b, p0/m, z0.b, z1.b
; TRANSFORM-NEXT:    mov z0.d, z2.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_mls_s8:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z2.d, z0.d
; NOTRANSFORM-NEXT:    mls z2.b, p0/m, z0.b, z1.b
; NOTRANSFORM-NEXT:    mls z2.b, p0/m, z0.b, z1.b
; NOTRANSFORM-NEXT:    mov z0.d, z2.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 16 x i8> @llvm.aarch64.sve.mls.nxv16i8(<vscale x 16 x i1> %pg, <vscale x 16 x i8> %a, <vscale x 16 x i8> %a, <vscale x 16 x i8> %b)
  %2 = tail call <vscale x 16 x i8> @llvm.aarch64.sve.mls.nxv16i8(<vscale x 16 x i1> %pg, <vscale x 16 x i8> %1, <vscale x 16 x i8> %a, <vscale x 16 x i8> %b)
  ret <vscale x 16 x i8> %2
}

define dso_local <vscale x 8 x i16> @test_mls_s16(<vscale x 8 x i1> %pg, <vscale x 8 x i16> %a, <vscale x 8 x i16> %b) {
; TRANSFORM-LABEL: test_mls_s16:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z2, z0
; TRANSFORM-NEXT:    mls z2.h, p0/m, z0.h, z1.h
; TRANSFORM-NEXT:    mls z2.h, p0/m, z0.h, z1.h
; TRANSFORM-NEXT:    mov z0.d, z2.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_mls_s16:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z2.d, z0.d
; NOTRANSFORM-NEXT:    mls z2.h, p0/m, z0.h, z1.h
; NOTRANSFORM-NEXT:    mls z2.h, p0/m, z0.h, z1.h
; NOTRANSFORM-NEXT:    mov z0.d, z2.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 8 x i16> @llvm.aarch64.sve.mls.nxv8i16(<vscale x 8 x i1> %pg, <vscale x 8 x i16> %a, <vscale x 8 x i16> %a, <vscale x 8 x i16> %b)
  %2 = tail call <vscale x 8 x i16> @llvm.aarch64.sve.mls.nxv8i16(<vscale x 8 x i1> %pg, <vscale x 8 x i16> %1, <vscale x 8 x i16> %a, <vscale x 8 x i16> %b)
  ret <vscale x 8 x i16> %2
}

define dso_local <vscale x 16 x i8> @test_mls_s8_multi_use(<vscale x 16 x i1> %pg, <vscale x 16 x i8> %a, <vscale x 16 x i8> %b) {
; TRANSFORM-LABEL: test_mls_s8_multi_use:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z2, z0
; TRANSFORM-NEXT:    mls z2.b, p0/m, z0.b, z1.b
; TRANSFORM-NEXT:    movprfx z3, z2
; TRANSFORM-NEXT:    mls z3.b, p0/m, z0.b, z1.b
; TRANSFORM-NEXT:    add z0.b, z2.b, z3.b
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_mls_s8_multi_use:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z2.d, z0.d
; NOTRANSFORM-NEXT:    mls z2.b, p0/m, z0.b, z1.b
; NOTRANSFORM-NEXT:    mov z3.d, z2.d
; NOTRANSFORM-NEXT:    mls z3.b, p0/m, z0.b, z1.b
; NOTRANSFORM-NEXT:    add z0.b, z2.b, z3.b
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 16 x i8> @llvm.aarch64.sve.mls.nxv16i8(<vscale x 16 x i1> %pg, <vscale x 16 x i8> %a, <vscale x 16 x i8> %a, <vscale x 16 x i8> %b)
  %2 = tail call <vscale x 16 x i8> @llvm.aarch64.sve.mls.nxv16i8(<vscale x 16 x i1> %pg, <vscale x 16 x i8> %1, <vscale x 16 x i8> %a, <vscale x 16 x i8> %b)
  %3 = add <vscale x 16 x i8> %1, %2
  ret <vscale x 16 x i8> %3
}

define dso_local <vscale x 8 x half> @test_fmad_f16(<vscale x 8 x i1> %pg, <vscale x 8 x half> %e) {
; TRANSFORM-LABEL: test_fmad_f16:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    fmad z1.h, p0/m, z0.h, z0.h
; TRANSFORM-NEXT:    fmad z0.h, p0/m, z0.h, z1.h
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_fmad_f16:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    fmad z1.h, p0/m, z0.h, z0.h
; NOTRANSFORM-NEXT:    fmad z0.h, p0/m, z0.h, z1.h
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 8 x half> @llvm.aarch64.sve.fmad.nxv8f16(<vscale x 8 x i1> %pg, <vscale x 8 x half> %e, <vscale x 8 x half> %e, <vscale x 8 x half> %e)
  %2 = tail call <vscale x 8 x half> @llvm.aarch64.sve.fmad.nxv8f16(<vscale x 8 x i1> %pg, <vscale x 8 x half> %e, <vscale x 8 x half> %e, <vscale x 8 x half> %1)
  ret <vscale x 8 x half> %2
}

define dso_local <vscale x 4 x float> @test_fmad_f32(<vscale x 4 x i1> %pg, <vscale x 4 x float> %e) {
; TRANSFORM-LABEL: test_fmad_f32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    fmad z1.s, p0/m, z0.s, z0.s
; TRANSFORM-NEXT:    fmad z0.s, p0/m, z0.s, z1.s
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_fmad_f32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    fmad z1.s, p0/m, z0.s, z0.s
; NOTRANSFORM-NEXT:    fmad z0.s, p0/m, z0.s, z1.s
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x float> @llvm.aarch64.sve.fmad.nxv4f32(<vscale x 4 x i1> %pg, <vscale x 4 x float> %e, <vscale x 4 x float> %e, <vscale x 4 x float> %e)
  %2 = tail call <vscale x 4 x float> @llvm.aarch64.sve.fmad.nxv4f32(<vscale x 4 x i1> %pg, <vscale x 4 x float> %e, <vscale x 4 x float> %e, <vscale x 4 x float> %1)
  ret <vscale x 4 x float> %2
}

define dso_local <vscale x 2 x double> @test_fmad_f64(<vscale x 2 x i1> %pg, <vscale x 2 x double> %e) {
; TRANSFORM-LABEL: test_fmad_f64:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    fmad z1.d, p0/m, z0.d, z0.d
; TRANSFORM-NEXT:    fmad z0.d, p0/m, z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_fmad_f64:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    fmad z1.d, p0/m, z0.d, z0.d
; NOTRANSFORM-NEXT:    fmad z0.d, p0/m, z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 2 x double> @llvm.aarch64.sve.fmad.nxv2f64(<vscale x 2 x i1> %pg, <vscale x 2 x double> %e, <vscale x 2 x double> %e, <vscale x 2 x double> %e)
  %2 = tail call <vscale x 2 x double> @llvm.aarch64.sve.fmad.nxv2f64(<vscale x 2 x i1> %pg, <vscale x 2 x double> %e, <vscale x 2 x double> %e, <vscale x 2 x double> %1)
  ret <vscale x 2 x double> %2
}

define dso_local <vscale x 2 x double> @test_fsqrt_f64(<vscale x 2 x i1> %pg, <vscale x 2 x double> %a, <vscale x 2 x double> %b) {
; TRANSFORM-LABEL: test_fsqrt_f64:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    fsqrt z0.d, p0/m, z0.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_fsqrt_f64:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    fsqrt z0.d, p0/m, z0.d
; NOTRANSFORM-NEXT:    ret
  %sqrt = tail call <vscale x 2 x double> @llvm.aarch64.sve.fsqrt.nxv2f64(<vscale x 2 x double> undef, <vscale x 2 x i1> %pg, <vscale x 2 x double> %a)
  ret <vscale x 2 x double> %sqrt
}

;; Group A remaining: MSB, FMSB, FNMAD, FNMSB

define dso_local <vscale x 4 x i32> @test_msb_s32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %e) {
; TRANSFORM-LABEL: test_msb_s32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    msb z1.s, p0/m, z0.s, z0.s
; TRANSFORM-NEXT:    msb z0.s, p0/m, z0.s, z1.s
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_msb_s32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    msb z1.s, p0/m, z0.s, z0.s
; NOTRANSFORM-NEXT:    msb z0.s, p0/m, z0.s, z1.s
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.msb.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %e, <vscale x 4 x i32> %e, <vscale x 4 x i32> %e)
  %2 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.msb.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %e, <vscale x 4 x i32> %e, <vscale x 4 x i32> %1)
  ret <vscale x 4 x i32> %2
}

define dso_local <vscale x 4 x float> @test_fmsb_f32(<vscale x 4 x i1> %pg, <vscale x 4 x float> %e) {
; TRANSFORM-LABEL: test_fmsb_f32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    fmsb z1.s, p0/m, z0.s, z0.s
; TRANSFORM-NEXT:    fmsb z0.s, p0/m, z0.s, z1.s
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_fmsb_f32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    fmsb z1.s, p0/m, z0.s, z0.s
; NOTRANSFORM-NEXT:    fmsb z0.s, p0/m, z0.s, z1.s
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x float> @llvm.aarch64.sve.fmsb.nxv4f32(<vscale x 4 x i1> %pg, <vscale x 4 x float> %e, <vscale x 4 x float> %e, <vscale x 4 x float> %e)
  %2 = tail call <vscale x 4 x float> @llvm.aarch64.sve.fmsb.nxv4f32(<vscale x 4 x i1> %pg, <vscale x 4 x float> %e, <vscale x 4 x float> %e, <vscale x 4 x float> %1)
  ret <vscale x 4 x float> %2
}

define dso_local <vscale x 4 x float> @test_fnmad_f32(<vscale x 4 x i1> %pg, <vscale x 4 x float> %e) {
; TRANSFORM-LABEL: test_fnmad_f32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    fnmad z1.s, p0/m, z0.s, z0.s
; TRANSFORM-NEXT:    fnmad z0.s, p0/m, z0.s, z1.s
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_fnmad_f32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    fnmad z1.s, p0/m, z0.s, z0.s
; NOTRANSFORM-NEXT:    fnmad z0.s, p0/m, z0.s, z1.s
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x float> @llvm.aarch64.sve.fnmad.nxv4f32(<vscale x 4 x i1> %pg, <vscale x 4 x float> %e, <vscale x 4 x float> %e, <vscale x 4 x float> %e)
  %2 = tail call <vscale x 4 x float> @llvm.aarch64.sve.fnmad.nxv4f32(<vscale x 4 x i1> %pg, <vscale x 4 x float> %e, <vscale x 4 x float> %e, <vscale x 4 x float> %1)
  ret <vscale x 4 x float> %2
}

define dso_local <vscale x 4 x float> @test_fnmsb_f32(<vscale x 4 x i1> %pg, <vscale x 4 x float> %e) {
; TRANSFORM-LABEL: test_fnmsb_f32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    fnmsb z1.s, p0/m, z0.s, z0.s
; TRANSFORM-NEXT:    fnmsb z0.s, p0/m, z0.s, z1.s
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_fnmsb_f32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    fnmsb z1.s, p0/m, z0.s, z0.s
; NOTRANSFORM-NEXT:    fnmsb z0.s, p0/m, z0.s, z1.s
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x float> @llvm.aarch64.sve.fnmsb.nxv4f32(<vscale x 4 x i1> %pg, <vscale x 4 x float> %e, <vscale x 4 x float> %e, <vscale x 4 x float> %e)
  %2 = tail call <vscale x 4 x float> @llvm.aarch64.sve.fnmsb.nxv4f32(<vscale x 4 x i1> %pg, <vscale x 4 x float> %e, <vscale x 4 x float> %e, <vscale x 4 x float> %1)
  ret <vscale x 4 x float> %2
}

;; ============================================================================
;; Group B: 5-op FCMLA (PredIdx=1, DOPIdx=2, SrcIdx=3, Src2Idx=4, Src3Idx=5)
;; ============================================================================

define dso_local <vscale x 4 x float> @test_fcmla_f32(<vscale x 4 x i1> %pg, <vscale x 4 x float> %e) {
; TRANSFORM-LABEL: test_fcmla_f32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    fcmla z1.s, p0/m, z0.s, z0.s, #0
; TRANSFORM-NEXT:    fcmla z0.s, p0/m, z0.s, z1.s, #0
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_fcmla_f32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    fcmla z1.s, p0/m, z0.s, z0.s, #0
; NOTRANSFORM-NEXT:    fcmla z0.s, p0/m, z0.s, z1.s, #0
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x float> @llvm.aarch64.sve.fcmla.nxv4f32(<vscale x 4 x i1> %pg, <vscale x 4 x float> %e, <vscale x 4 x float> %e, <vscale x 4 x float> %e, i32 0)
  %2 = tail call <vscale x 4 x float> @llvm.aarch64.sve.fcmla.nxv4f32(<vscale x 4 x i1> %pg, <vscale x 4 x float> %e, <vscale x 4 x float> %e, <vscale x 4 x float> %1, i32 0)
  ret <vscale x 4 x float> %2
}

;; ============================================================================
;; Group C: 4-op predicated binary (PredIdx=1, DOPIdx=2, SrcIdx=3)
;; ============================================================================

define dso_local <vscale x 4 x i32> @test_shadd_s32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a) {
; TRANSFORM-LABEL: test_shadd_s32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    shadd z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    shadd z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_shadd_s32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    shadd z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    shadd z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.shadd.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  %2 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.shadd.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %1, <vscale x 4 x i32> %a)
  ret <vscale x 4 x i32> %2
}

define dso_local <vscale x 4 x i32> @test_uhadd_s32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a) {
; TRANSFORM-LABEL: test_uhadd_s32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    uhadd z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    uhadd z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_uhadd_s32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    uhadd z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    uhadd z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.uhadd.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  %2 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.uhadd.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %1, <vscale x 4 x i32> %a)
  ret <vscale x 4 x i32> %2
}

define dso_local <vscale x 4 x i32> @test_shsub_s32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a) {
; TRANSFORM-LABEL: test_shsub_s32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    shsub z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    shsub z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_shsub_s32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    shsub z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    shsub z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.shsub.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  %2 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.shsub.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %1, <vscale x 4 x i32> %a)
  ret <vscale x 4 x i32> %2
}

define dso_local <vscale x 4 x i32> @test_uhsub_s32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a) {
; TRANSFORM-LABEL: test_uhsub_s32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    uhsub z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    uhsub z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_uhsub_s32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    uhsub z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    uhsub z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.uhsub.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  %2 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.uhsub.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %1, <vscale x 4 x i32> %a)
  ret <vscale x 4 x i32> %2
}

define dso_local <vscale x 4 x i32> @test_shsubr_s32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a) {
; TRANSFORM-LABEL: test_shsubr_s32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    shsubr z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    shsubr z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_shsubr_s32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    shsubr z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    shsubr z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.shsubr.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  %2 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.shsubr.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %1, <vscale x 4 x i32> %a)
  ret <vscale x 4 x i32> %2
}

define dso_local <vscale x 4 x i32> @test_uhsubr_s32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a) {
; TRANSFORM-LABEL: test_uhsubr_s32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    uhsubr z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    uhsubr z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_uhsubr_s32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    uhsubr z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    uhsubr z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.uhsubr.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  %2 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.uhsubr.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %1, <vscale x 4 x i32> %a)
  ret <vscale x 4 x i32> %2
}

define dso_local <vscale x 4 x i32> @test_srhadd_s32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a) {
; TRANSFORM-LABEL: test_srhadd_s32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    srhadd z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    srhadd z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_srhadd_s32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    srhadd z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    srhadd z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.srhadd.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  %2 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.srhadd.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %1, <vscale x 4 x i32> %a)
  ret <vscale x 4 x i32> %2
}

define dso_local <vscale x 4 x i32> @test_urhadd_s32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a) {
; TRANSFORM-LABEL: test_urhadd_s32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    urhadd z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    urhadd z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_urhadd_s32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    urhadd z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    urhadd z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.urhadd.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  %2 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.urhadd.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %1, <vscale x 4 x i32> %a)
  ret <vscale x 4 x i32> %2
}

define dso_local <vscale x 4 x i32> @test_sqadd_s32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a) {
; TRANSFORM-LABEL: test_sqadd_s32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    sqadd z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    sqadd z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_sqadd_s32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    sqadd z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    sqadd z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.sqadd.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  %2 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.sqadd.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %1, <vscale x 4 x i32> %a)
  ret <vscale x 4 x i32> %2
}

define dso_local <vscale x 4 x i32> @test_uqadd_s32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a) {
; TRANSFORM-LABEL: test_uqadd_s32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    uqadd z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    uqadd z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_uqadd_s32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    uqadd z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    uqadd z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.uqadd.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  %2 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.uqadd.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %1, <vscale x 4 x i32> %a)
  ret <vscale x 4 x i32> %2
}

define dso_local <vscale x 4 x i32> @test_sqsub_s32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a) {
; TRANSFORM-LABEL: test_sqsub_s32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    sqsub z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    sqsub z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_sqsub_s32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    sqsub z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    sqsub z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.sqsub.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  %2 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.sqsub.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %1, <vscale x 4 x i32> %a)
  ret <vscale x 4 x i32> %2
}

define dso_local <vscale x 4 x i32> @test_uqsub_s32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a) {
; TRANSFORM-LABEL: test_uqsub_s32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    uqsub z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    uqsub z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_uqsub_s32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    uqsub z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    uqsub z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.uqsub.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  %2 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.uqsub.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %1, <vscale x 4 x i32> %a)
  ret <vscale x 4 x i32> %2
}

define dso_local <vscale x 4 x i32> @test_suqadd_s32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a) {
; TRANSFORM-LABEL: test_suqadd_s32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    suqadd z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    suqadd z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_suqadd_s32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    suqadd z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    suqadd z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.suqadd.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  %2 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.suqadd.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %1, <vscale x 4 x i32> %a)
  ret <vscale x 4 x i32> %2
}

define dso_local <vscale x 4 x i32> @test_usqadd_s32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a) {
; TRANSFORM-LABEL: test_usqadd_s32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    usqadd z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    usqadd z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_usqadd_s32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    usqadd z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    usqadd z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.usqadd.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  %2 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.usqadd.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %1, <vscale x 4 x i32> %a)
  ret <vscale x 4 x i32> %2
}

define dso_local <vscale x 4 x i32> @test_sqsubr_s32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a) {
; TRANSFORM-LABEL: test_sqsubr_s32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    sqsubr z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    sqsubr z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_sqsubr_s32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    sqsubr z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    sqsubr z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.sqsubr.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  %2 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.sqsubr.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %1, <vscale x 4 x i32> %a)
  ret <vscale x 4 x i32> %2
}

define dso_local <vscale x 4 x i32> @test_uqsubr_s32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a) {
; TRANSFORM-LABEL: test_uqsubr_s32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    uqsubr z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    uqsubr z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_uqsubr_s32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    uqsubr z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    uqsubr z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.uqsubr.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  %2 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.uqsubr.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %1, <vscale x 4 x i32> %a)
  ret <vscale x 4 x i32> %2
}

define dso_local <vscale x 4 x i32> @test_addp_s32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a) {
; TRANSFORM-LABEL: test_addp_s32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    addp z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    addp z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_addp_s32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    addp z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    addp z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.addp.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  %2 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.addp.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %1, <vscale x 4 x i32> %a)
  ret <vscale x 4 x i32> %2
}

define dso_local <vscale x 2 x i64> @test_sadalp_s64(<vscale x 2 x i1> %pg, <vscale x 4 x i32> %a) {
; TRANSFORM-LABEL: test_sadalp_s64:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    sadalp z1.d, p0/m, z0.s
; TRANSFORM-NEXT:    sadalp z1.d, p0/m, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_sadalp_s64:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    sadalp z1.d, p0/m, z0.s
; NOTRANSFORM-NEXT:    sadalp z1.d, p0/m, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.sadalp.nxv2i64(<vscale x 2 x i1> %pg, <vscale x 2 x i64> poison, <vscale x 4 x i32> %a)
  %2 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.sadalp.nxv2i64(<vscale x 2 x i1> %pg, <vscale x 2 x i64> %1, <vscale x 4 x i32> %a)
  ret <vscale x 2 x i64> %2
}

define dso_local <vscale x 2 x i64> @test_uadalp_s64(<vscale x 2 x i1> %pg, <vscale x 4 x i32> %a) {
; TRANSFORM-LABEL: test_uadalp_s64:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    uadalp z1.d, p0/m, z0.s
; TRANSFORM-NEXT:    uadalp z1.d, p0/m, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_uadalp_s64:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    uadalp z1.d, p0/m, z0.s
; NOTRANSFORM-NEXT:    uadalp z1.d, p0/m, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.uadalp.nxv2i64(<vscale x 2 x i1> %pg, <vscale x 2 x i64> poison, <vscale x 4 x i32> %a)
  %2 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.uadalp.nxv2i64(<vscale x 2 x i1> %pg, <vscale x 2 x i64> %1, <vscale x 4 x i32> %a)
  ret <vscale x 2 x i64> %2
}

define dso_local <vscale x 4 x i32> @test_smaxp_s32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a) {
; TRANSFORM-LABEL: test_smaxp_s32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    smaxp z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    smaxp z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_smaxp_s32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    smaxp z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    smaxp z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.smaxp.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  %2 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.smaxp.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %1, <vscale x 4 x i32> %a)
  ret <vscale x 4 x i32> %2
}

define dso_local <vscale x 4 x i32> @test_umaxp_s32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a) {
; TRANSFORM-LABEL: test_umaxp_s32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    umaxp z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    umaxp z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_umaxp_s32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    umaxp z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    umaxp z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.umaxp.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  %2 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.umaxp.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %1, <vscale x 4 x i32> %a)
  ret <vscale x 4 x i32> %2
}

define dso_local <vscale x 4 x i32> @test_sminp_s32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a) {
; TRANSFORM-LABEL: test_sminp_s32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    sminp z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    sminp z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_sminp_s32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    sminp z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    sminp z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.sminp.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  %2 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.sminp.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %1, <vscale x 4 x i32> %a)
  ret <vscale x 4 x i32> %2
}

define dso_local <vscale x 4 x i32> @test_uminp_s32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a) {
; TRANSFORM-LABEL: test_uminp_s32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    uminp z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    uminp z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_uminp_s32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    uminp z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    uminp z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.uminp.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  %2 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.uminp.nxv4i32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %1, <vscale x 4 x i32> %a)
  ret <vscale x 4 x i32> %2
}

define dso_local <vscale x 4 x float> @test_fabd_f32(<vscale x 4 x i1> %pg, <vscale x 4 x float> %a) {
; TRANSFORM-LABEL: test_fabd_f32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    fabd z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    fabd z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_fabd_f32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    fabd z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    fabd z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x float> @llvm.aarch64.sve.fabd.nxv4f32(<vscale x 4 x i1> %pg, <vscale x 4 x float> %a, <vscale x 4 x float> %a)
  %2 = tail call <vscale x 4 x float> @llvm.aarch64.sve.fabd.nxv4f32(<vscale x 4 x i1> %pg, <vscale x 4 x float> %1, <vscale x 4 x float> %a)
  ret <vscale x 4 x float> %2
}

define dso_local <vscale x 4 x float> @test_faddp_f32(<vscale x 4 x i1> %pg, <vscale x 4 x float> %a) {
; TRANSFORM-LABEL: test_faddp_f32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    faddp z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    faddp z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_faddp_f32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    faddp z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    faddp z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x float> @llvm.aarch64.sve.faddp.nxv4f32(<vscale x 4 x i1> %pg, <vscale x 4 x float> %a, <vscale x 4 x float> %a)
  %2 = tail call <vscale x 4 x float> @llvm.aarch64.sve.faddp.nxv4f32(<vscale x 4 x i1> %pg, <vscale x 4 x float> %1, <vscale x 4 x float> %a)
  ret <vscale x 4 x float> %2
}

define dso_local <vscale x 4 x float> @test_fcadd_f32(<vscale x 4 x i1> %pg, <vscale x 4 x float> %a, <vscale x 4 x float> %b) {
; TRANSFORM-LABEL: test_fcadd_f32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    fcadd z0.s, p0/m, z0.s, z0.s, #90
; TRANSFORM-NEXT:    fcadd z0.s, p0/m, z0.s, z1.s, #90
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_fcadd_f32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    fcadd z0.s, p0/m, z0.s, z0.s, #90
; NOTRANSFORM-NEXT:    fcadd z0.s, p0/m, z0.s, z1.s, #90
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x float> @llvm.aarch64.sve.fcadd.nxv4f32(<vscale x 4 x i1> %pg, <vscale x 4 x float> %a, <vscale x 4 x float> %a, i32 90)
  %2 = tail call <vscale x 4 x float> @llvm.aarch64.sve.fcadd.nxv4f32(<vscale x 4 x i1> %pg, <vscale x 4 x float> %1, <vscale x 4 x float> %b, i32 90)
  ret <vscale x 4 x float> %2
}

define dso_local <vscale x 4 x float> @test_fmaxnmp_f32(<vscale x 4 x i1> %pg, <vscale x 4 x float> %a) {
; TRANSFORM-LABEL: test_fmaxnmp_f32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    fmaxnmp z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    fmaxnmp z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_fmaxnmp_f32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    fmaxnmp z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    fmaxnmp z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x float> @llvm.aarch64.sve.fmaxnmp.nxv4f32(<vscale x 4 x i1> %pg, <vscale x 4 x float> %a, <vscale x 4 x float> %a)
  %2 = tail call <vscale x 4 x float> @llvm.aarch64.sve.fmaxnmp.nxv4f32(<vscale x 4 x i1> %pg, <vscale x 4 x float> %1, <vscale x 4 x float> %a)
  ret <vscale x 4 x float> %2
}

define dso_local <vscale x 4 x float> @test_fminnmp_f32(<vscale x 4 x i1> %pg, <vscale x 4 x float> %a) {
; TRANSFORM-LABEL: test_fminnmp_f32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    fminnmp z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    fminnmp z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_fminnmp_f32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    fminnmp z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    fminnmp z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x float> @llvm.aarch64.sve.fminnmp.nxv4f32(<vscale x 4 x i1> %pg, <vscale x 4 x float> %a, <vscale x 4 x float> %a)
  %2 = tail call <vscale x 4 x float> @llvm.aarch64.sve.fminnmp.nxv4f32(<vscale x 4 x i1> %pg, <vscale x 4 x float> %1, <vscale x 4 x float> %a)
  ret <vscale x 4 x float> %2
}

define dso_local <vscale x 4 x float> @test_fmaxp_f32(<vscale x 4 x i1> %pg, <vscale x 4 x float> %a) {
; TRANSFORM-LABEL: test_fmaxp_f32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    fmaxp z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    fmaxp z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_fmaxp_f32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    fmaxp z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    fmaxp z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x float> @llvm.aarch64.sve.fmaxp.nxv4f32(<vscale x 4 x i1> %pg, <vscale x 4 x float> %a, <vscale x 4 x float> %a)
  %2 = tail call <vscale x 4 x float> @llvm.aarch64.sve.fmaxp.nxv4f32(<vscale x 4 x i1> %pg, <vscale x 4 x float> %1, <vscale x 4 x float> %a)
  ret <vscale x 4 x float> %2
}

define dso_local <vscale x 4 x float> @test_fminp_f32(<vscale x 4 x i1> %pg, <vscale x 4 x float> %a) {
; TRANSFORM-LABEL: test_fminp_f32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    fminp z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    fminp z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_fminp_f32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    fminp z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    fminp z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x float> @llvm.aarch64.sve.fminp.nxv4f32(<vscale x 4 x i1> %pg, <vscale x 4 x float> %a, <vscale x 4 x float> %a)
  %2 = tail call <vscale x 4 x float> @llvm.aarch64.sve.fminp.nxv4f32(<vscale x 4 x i1> %pg, <vscale x 4 x float> %1, <vscale x 4 x float> %a)
  ret <vscale x 4 x float> %2
}

define dso_local <vscale x 4 x float> @test_fscale_f32(<vscale x 4 x i1> %pg, <vscale x 4 x float> %a) {
; TRANSFORM-LABEL: test_fscale_f32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    mov z1.s, #0 // =0x0
; TRANSFORM-NEXT:    fscale z0.s, p0/m, z0.s, z1.s
; TRANSFORM-NEXT:    fscale z0.s, p0/m, z0.s, z1.s
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_fscale_f32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.s, #0 // =0x0
; NOTRANSFORM-NEXT:    fscale z0.s, p0/m, z0.s, z1.s
; NOTRANSFORM-NEXT:    fscale z0.s, p0/m, z0.s, z1.s
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x float> @llvm.aarch64.sve.fscale.nxv4f32(<vscale x 4 x i1> %pg, <vscale x 4 x float> poison, <vscale x 4 x i32> zeroinitializer)
  %2 = tail call <vscale x 4 x float> @llvm.aarch64.sve.fscale.nxv4f32(<vscale x 4 x i1> %pg, <vscale x 4 x float> %1, <vscale x 4 x i32> zeroinitializer)
  ret <vscale x 4 x float> %2
}

define dso_local <vscale x 4 x float> @test_fmulx_f32(<vscale x 4 x i1> %pg, <vscale x 4 x float> %a) {
; TRANSFORM-LABEL: test_fmulx_f32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    fmulx z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    fmulx z1.s, p0/m, z1.s, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_fmulx_f32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    fmulx z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    fmulx z1.s, p0/m, z1.s, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x float> @llvm.aarch64.sve.fmulx.nxv4f32(<vscale x 4 x i1> %pg, <vscale x 4 x float> %a, <vscale x 4 x float> %a)
  %2 = tail call <vscale x 4 x float> @llvm.aarch64.sve.fmulx.nxv4f32(<vscale x 4 x i1> %pg, <vscale x 4 x float> %1, <vscale x 4 x float> %a)
  ret <vscale x 4 x float> %2
}

;; ============================================================================
;; Group D: 3-op predicated unary (PredIdx=2, DOPIdx=1, SrcIdx=3)
;; ============================================================================

define dso_local <vscale x 4 x i32> @test_sqabs_s32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a) {
; TRANSFORM-LABEL: test_sqabs_s32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    sqabs z1.s, p0/m, z0.s
; TRANSFORM-NEXT:    sqabs z1.s, p0/m, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_sqabs_s32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    sqabs z1.s, p0/m, z0.s
; NOTRANSFORM-NEXT:    sqabs z1.s, p0/m, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.sqabs.nxv4i32(<vscale x 4 x i32> %a, <vscale x 4 x i1> %pg, <vscale x 4 x i32> %a)
  %2 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.sqabs.nxv4i32(<vscale x 4 x i32> %1, <vscale x 4 x i1> %pg, <vscale x 4 x i32> %a)
  ret <vscale x 4 x i32> %2
}

define dso_local <vscale x 4 x i32> @test_sqneg_s32(<vscale x 4 x i1> %pg, <vscale x 4 x i32> %a) {
; TRANSFORM-LABEL: test_sqneg_s32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    sqneg z1.s, p0/m, z0.s
; TRANSFORM-NEXT:    sqneg z1.s, p0/m, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_sqneg_s32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    sqneg z1.s, p0/m, z0.s
; NOTRANSFORM-NEXT:    sqneg z1.s, p0/m, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.sqneg.nxv4i32(<vscale x 4 x i32> %a, <vscale x 4 x i1> %pg, <vscale x 4 x i32> %a)
  %2 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.sqneg.nxv4i32(<vscale x 4 x i32> %1, <vscale x 4 x i1> %pg, <vscale x 4 x i32> %a)
  ret <vscale x 4 x i32> %2
}

;; ============================================================================
;; Group E: 3-op no-predicate (DOPIdx=1, SrcIdx=2, Src2Idx=3)
;; ============================================================================

define dso_local <vscale x 4 x i32> @test_bsl_s32(<vscale x 4 x i32> %a, <vscale x 4 x i32> %b) {
; TRANSFORM-LABEL: test_bsl_s32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z2, z0
; TRANSFORM-NEXT:    bsl z2.d, z2.d, z0.d, z1.d
; TRANSFORM-NEXT:    bsl z2.d, z2.d, z0.d, z1.d
; TRANSFORM-NEXT:    mov z0.d, z2.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_bsl_s32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z2.d, z0.d
; NOTRANSFORM-NEXT:    bsl z2.d, z2.d, z0.d, z1.d
; NOTRANSFORM-NEXT:    bsl z2.d, z2.d, z0.d, z1.d
; NOTRANSFORM-NEXT:    mov z0.d, z2.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.bsl.nxv4i32(<vscale x 4 x i32> %a, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b)
  %2 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.bsl.nxv4i32(<vscale x 4 x i32> %1, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b)
  ret <vscale x 4 x i32> %2
}

define dso_local <vscale x 4 x i32> @test_bsl1n_s32(<vscale x 4 x i32> %a, <vscale x 4 x i32> %b) {
; TRANSFORM-LABEL: test_bsl1n_s32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z2, z0
; TRANSFORM-NEXT:    bsl1n z2.d, z2.d, z0.d, z1.d
; TRANSFORM-NEXT:    bsl1n z2.d, z2.d, z0.d, z1.d
; TRANSFORM-NEXT:    mov z0.d, z2.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_bsl1n_s32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z2.d, z0.d
; NOTRANSFORM-NEXT:    bsl1n z2.d, z2.d, z0.d, z1.d
; NOTRANSFORM-NEXT:    bsl1n z2.d, z2.d, z0.d, z1.d
; NOTRANSFORM-NEXT:    mov z0.d, z2.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.bsl1n.nxv4i32(<vscale x 4 x i32> %a, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b)
  %2 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.bsl1n.nxv4i32(<vscale x 4 x i32> %1, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b)
  ret <vscale x 4 x i32> %2
}

define dso_local <vscale x 4 x i32> @test_bsl2n_s32(<vscale x 4 x i32> %a, <vscale x 4 x i32> %b) {
; TRANSFORM-LABEL: test_bsl2n_s32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z2, z0
; TRANSFORM-NEXT:    bsl2n z2.d, z2.d, z0.d, z1.d
; TRANSFORM-NEXT:    bsl2n z2.d, z2.d, z0.d, z1.d
; TRANSFORM-NEXT:    mov z0.d, z2.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_bsl2n_s32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z2.d, z0.d
; NOTRANSFORM-NEXT:    bsl2n z2.d, z2.d, z0.d, z1.d
; NOTRANSFORM-NEXT:    bsl2n z2.d, z2.d, z0.d, z1.d
; NOTRANSFORM-NEXT:    mov z0.d, z2.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.bsl2n.nxv4i32(<vscale x 4 x i32> %a, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b)
  %2 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.bsl2n.nxv4i32(<vscale x 4 x i32> %1, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b)
  ret <vscale x 4 x i32> %2
}

define dso_local <vscale x 4 x i32> @test_nbsl_s32(<vscale x 4 x i32> %a, <vscale x 4 x i32> %b) {
; TRANSFORM-LABEL: test_nbsl_s32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z2, z0
; TRANSFORM-NEXT:    nbsl z2.d, z2.d, z0.d, z1.d
; TRANSFORM-NEXT:    nbsl z2.d, z2.d, z0.d, z1.d
; TRANSFORM-NEXT:    mov z0.d, z2.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_nbsl_s32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z2.d, z0.d
; NOTRANSFORM-NEXT:    nbsl z2.d, z2.d, z0.d, z1.d
; NOTRANSFORM-NEXT:    nbsl z2.d, z2.d, z0.d, z1.d
; NOTRANSFORM-NEXT:    mov z0.d, z2.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.nbsl.nxv4i32(<vscale x 4 x i32> %a, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b)
  %2 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.nbsl.nxv4i32(<vscale x 4 x i32> %1, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b)
  ret <vscale x 4 x i32> %2
}

define dso_local <vscale x 4 x i32> @test_eor3_s32(<vscale x 4 x i32> %a, <vscale x 4 x i32> %b) {
; TRANSFORM-LABEL: test_eor3_s32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z2, z0
; TRANSFORM-NEXT:    eor3 z2.d, z2.d, z0.d, z1.d
; TRANSFORM-NEXT:    eor3 z2.d, z2.d, z0.d, z1.d
; TRANSFORM-NEXT:    mov z0.d, z2.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_eor3_s32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z2.d, z0.d
; NOTRANSFORM-NEXT:    eor3 z2.d, z2.d, z0.d, z1.d
; NOTRANSFORM-NEXT:    eor3 z2.d, z2.d, z0.d, z1.d
; NOTRANSFORM-NEXT:    mov z0.d, z2.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.eor3.nxv4i32(<vscale x 4 x i32> %a, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b)
  %2 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.eor3.nxv4i32(<vscale x 4 x i32> %1, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b)
  ret <vscale x 4 x i32> %2
}

define dso_local <vscale x 4 x i32> @test_bcax_s32(<vscale x 4 x i32> %a, <vscale x 4 x i32> %b) {
; TRANSFORM-LABEL: test_bcax_s32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z2, z0
; TRANSFORM-NEXT:    bcax z2.d, z2.d, z0.d, z1.d
; TRANSFORM-NEXT:    bcax z2.d, z2.d, z0.d, z1.d
; TRANSFORM-NEXT:    mov z0.d, z2.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_bcax_s32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z2.d, z0.d
; NOTRANSFORM-NEXT:    bcax z2.d, z2.d, z0.d, z1.d
; NOTRANSFORM-NEXT:    bcax z2.d, z2.d, z0.d, z1.d
; NOTRANSFORM-NEXT:    mov z0.d, z2.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.bcax.nxv4i32(<vscale x 4 x i32> %a, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b)
  %2 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.bcax.nxv4i32(<vscale x 4 x i32> %1, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b)
  ret <vscale x 4 x i32> %2
}

define dso_local <vscale x 4 x i32> @test_xar_s32(<vscale x 4 x i32> %a, <vscale x 4 x i32> %b) {
; TRANSFORM-LABEL: test_xar_s32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    xar z0.s, z0.s, z1.s, #3
; TRANSFORM-NEXT:    xar z0.s, z0.s, z1.s, #3
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_xar_s32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    xar z0.s, z0.s, z1.s, #3
; NOTRANSFORM-NEXT:    xar z0.s, z0.s, z1.s, #3
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.xar.nxv4i32(<vscale x 4 x i32> %a, <vscale x 4 x i32> %b, i32 3)
  %2 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.xar.nxv4i32(<vscale x 4 x i32> %1, <vscale x 4 x i32> %b, i32 3)
  ret <vscale x 4 x i32> %2
}

define dso_local <vscale x 4 x i32> @test_sqrdmlah_s32(<vscale x 4 x i32> %a, <vscale x 4 x i32> %b) {
; TRANSFORM-LABEL: test_sqrdmlah_s32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z2, z0
; TRANSFORM-NEXT:    sqrdmlah z2.s, z0.s, z1.s
; TRANSFORM-NEXT:    sqrdmlah z2.s, z0.s, z1.s
; TRANSFORM-NEXT:    mov z0.d, z2.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_sqrdmlah_s32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z2.d, z0.d
; NOTRANSFORM-NEXT:    sqrdmlah z2.s, z0.s, z1.s
; NOTRANSFORM-NEXT:    sqrdmlah z2.s, z0.s, z1.s
; NOTRANSFORM-NEXT:    mov z0.d, z2.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.sqrdmlah.nxv4i32(<vscale x 4 x i32> %a, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b)
  %2 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.sqrdmlah.nxv4i32(<vscale x 4 x i32> %1, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b)
  ret <vscale x 4 x i32> %2
}

define dso_local <vscale x 4 x i32> @test_sqrdmlsh_s32(<vscale x 4 x i32> %a, <vscale x 4 x i32> %b) {
; TRANSFORM-LABEL: test_sqrdmlsh_s32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z2, z0
; TRANSFORM-NEXT:    sqrdmlsh z2.s, z0.s, z1.s
; TRANSFORM-NEXT:    sqrdmlsh z2.s, z0.s, z1.s
; TRANSFORM-NEXT:    mov z0.d, z2.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_sqrdmlsh_s32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z2.d, z0.d
; NOTRANSFORM-NEXT:    sqrdmlsh z2.s, z0.s, z1.s
; NOTRANSFORM-NEXT:    sqrdmlsh z2.s, z0.s, z1.s
; NOTRANSFORM-NEXT:    mov z0.d, z2.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.sqrdmlsh.nxv4i32(<vscale x 4 x i32> %a, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b)
  %2 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.sqrdmlsh.nxv4i32(<vscale x 4 x i32> %1, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b)
  ret <vscale x 4 x i32> %2
}

define dso_local <vscale x 2 x i64> @test_smlalb_s64(<vscale x 4 x i32> %a, <vscale x 4 x i32> %b) {
; TRANSFORM-LABEL: test_smlalb_s64:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    smlalb z1.d, z0.s, z0.s
; TRANSFORM-NEXT:    smlalb z1.d, z0.s, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_smlalb_s64:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    smlalb z1.d, z0.s, z0.s
; NOTRANSFORM-NEXT:    smlalb z1.d, z0.s, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.smlalb.nxv2i64(<vscale x 2 x i64> poison, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  %2 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.smlalb.nxv2i64(<vscale x 2 x i64> %1, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  ret <vscale x 2 x i64> %2
}

define dso_local <vscale x 2 x i64> @test_smlalt_s64(<vscale x 4 x i32> %a, <vscale x 4 x i32> %b) {
; TRANSFORM-LABEL: test_smlalt_s64:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    smlalt z1.d, z0.s, z0.s
; TRANSFORM-NEXT:    smlalt z1.d, z0.s, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_smlalt_s64:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    smlalt z1.d, z0.s, z0.s
; NOTRANSFORM-NEXT:    smlalt z1.d, z0.s, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.smlalt.nxv2i64(<vscale x 2 x i64> poison, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  %2 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.smlalt.nxv2i64(<vscale x 2 x i64> %1, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  ret <vscale x 2 x i64> %2
}

define dso_local <vscale x 2 x i64> @test_smlslb_s64(<vscale x 4 x i32> %a, <vscale x 4 x i32> %b) {
; TRANSFORM-LABEL: test_smlslb_s64:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    smlslb z1.d, z0.s, z0.s
; TRANSFORM-NEXT:    smlslb z1.d, z0.s, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_smlslb_s64:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    smlslb z1.d, z0.s, z0.s
; NOTRANSFORM-NEXT:    smlslb z1.d, z0.s, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.smlslb.nxv2i64(<vscale x 2 x i64> poison, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  %2 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.smlslb.nxv2i64(<vscale x 2 x i64> %1, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  ret <vscale x 2 x i64> %2
}

define dso_local <vscale x 2 x i64> @test_smlslt_s64(<vscale x 4 x i32> %a, <vscale x 4 x i32> %b) {
; TRANSFORM-LABEL: test_smlslt_s64:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    smlslt z1.d, z0.s, z0.s
; TRANSFORM-NEXT:    smlslt z1.d, z0.s, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_smlslt_s64:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    smlslt z1.d, z0.s, z0.s
; NOTRANSFORM-NEXT:    smlslt z1.d, z0.s, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.smlslt.nxv2i64(<vscale x 2 x i64> poison, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  %2 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.smlslt.nxv2i64(<vscale x 2 x i64> %1, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  ret <vscale x 2 x i64> %2
}

define dso_local <vscale x 2 x i64> @test_umlslb_s64(<vscale x 4 x i32> %a, <vscale x 4 x i32> %b) {
; TRANSFORM-LABEL: test_umlslb_s64:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    umlslb z1.d, z0.s, z0.s
; TRANSFORM-NEXT:    umlslb z1.d, z0.s, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_umlslb_s64:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    umlslb z1.d, z0.s, z0.s
; NOTRANSFORM-NEXT:    umlslb z1.d, z0.s, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.umlslb.nxv2i64(<vscale x 2 x i64> poison, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  %2 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.umlslb.nxv2i64(<vscale x 2 x i64> %1, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  ret <vscale x 2 x i64> %2
}

define dso_local <vscale x 2 x i64> @test_umlslt_s64(<vscale x 4 x i32> %a, <vscale x 4 x i32> %b) {
; TRANSFORM-LABEL: test_umlslt_s64:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    umlslt z1.d, z0.s, z0.s
; TRANSFORM-NEXT:    umlslt z1.d, z0.s, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_umlslt_s64:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    umlslt z1.d, z0.s, z0.s
; NOTRANSFORM-NEXT:    umlslt z1.d, z0.s, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.umlslt.nxv2i64(<vscale x 2 x i64> poison, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  %2 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.umlslt.nxv2i64(<vscale x 2 x i64> %1, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  ret <vscale x 2 x i64> %2
}

define dso_local <vscale x 2 x i64> @test_sqdmlalb_s64(<vscale x 4 x i32> %a, <vscale x 4 x i32> %b) {
; TRANSFORM-LABEL: test_sqdmlalb_s64:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    sqdmlalb z1.d, z0.s, z0.s
; TRANSFORM-NEXT:    sqdmlalb z1.d, z0.s, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_sqdmlalb_s64:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    sqdmlalb z1.d, z0.s, z0.s
; NOTRANSFORM-NEXT:    sqdmlalb z1.d, z0.s, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.sqdmlalb.nxv2i64(<vscale x 2 x i64> poison, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  %2 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.sqdmlalb.nxv2i64(<vscale x 2 x i64> %1, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  ret <vscale x 2 x i64> %2
}

define dso_local <vscale x 2 x i64> @test_sqdmlalt_s64(<vscale x 4 x i32> %a, <vscale x 4 x i32> %b) {
; TRANSFORM-LABEL: test_sqdmlalt_s64:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    sqdmlalt z1.d, z0.s, z0.s
; TRANSFORM-NEXT:    sqdmlalt z1.d, z0.s, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_sqdmlalt_s64:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    sqdmlalt z1.d, z0.s, z0.s
; NOTRANSFORM-NEXT:    sqdmlalt z1.d, z0.s, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.sqdmlalt.nxv2i64(<vscale x 2 x i64> poison, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  %2 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.sqdmlalt.nxv2i64(<vscale x 2 x i64> %1, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  ret <vscale x 2 x i64> %2
}

define dso_local <vscale x 2 x i64> @test_sqdmlslb_s64(<vscale x 4 x i32> %a, <vscale x 4 x i32> %b) {
; TRANSFORM-LABEL: test_sqdmlslb_s64:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    sqdmlslb z1.d, z0.s, z0.s
; TRANSFORM-NEXT:    sqdmlslb z1.d, z0.s, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_sqdmlslb_s64:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    sqdmlslb z1.d, z0.s, z0.s
; NOTRANSFORM-NEXT:    sqdmlslb z1.d, z0.s, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.sqdmlslb.nxv2i64(<vscale x 2 x i64> poison, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  %2 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.sqdmlslb.nxv2i64(<vscale x 2 x i64> %1, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  ret <vscale x 2 x i64> %2
}

define dso_local <vscale x 2 x i64> @test_sqdmlslt_s64(<vscale x 4 x i32> %a, <vscale x 4 x i32> %b) {
; TRANSFORM-LABEL: test_sqdmlslt_s64:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    sqdmlslt z1.d, z0.s, z0.s
; TRANSFORM-NEXT:    sqdmlslt z1.d, z0.s, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_sqdmlslt_s64:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    sqdmlslt z1.d, z0.s, z0.s
; NOTRANSFORM-NEXT:    sqdmlslt z1.d, z0.s, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.sqdmlslt.nxv2i64(<vscale x 2 x i64> poison, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  %2 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.sqdmlslt.nxv2i64(<vscale x 2 x i64> %1, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  ret <vscale x 2 x i64> %2
}

define dso_local <vscale x 2 x i64> @test_sqdmlalbt_s64(<vscale x 4 x i32> %a, <vscale x 4 x i32> %b) {
; TRANSFORM-LABEL: test_sqdmlalbt_s64:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    sqdmlalbt z1.d, z0.s, z0.s
; TRANSFORM-NEXT:    sqdmlalbt z1.d, z0.s, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_sqdmlalbt_s64:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    sqdmlalbt z1.d, z0.s, z0.s
; NOTRANSFORM-NEXT:    sqdmlalbt z1.d, z0.s, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.sqdmlalbt.nxv2i64(<vscale x 2 x i64> poison, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  %2 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.sqdmlalbt.nxv2i64(<vscale x 2 x i64> %1, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  ret <vscale x 2 x i64> %2
}

define dso_local <vscale x 2 x i64> @test_sqdmlslbt_s64(<vscale x 4 x i32> %a, <vscale x 4 x i32> %b) {
; TRANSFORM-LABEL: test_sqdmlslbt_s64:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    sqdmlslbt z1.d, z0.s, z0.s
; TRANSFORM-NEXT:    sqdmlslbt z1.d, z0.s, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_sqdmlslbt_s64:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    sqdmlslbt z1.d, z0.s, z0.s
; NOTRANSFORM-NEXT:    sqdmlslbt z1.d, z0.s, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.sqdmlslbt.nxv2i64(<vscale x 2 x i64> poison, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  %2 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.sqdmlslbt.nxv2i64(<vscale x 2 x i64> %1, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  ret <vscale x 2 x i64> %2
}

define dso_local <vscale x 2 x i64> @test_adclb_s64(<vscale x 2 x i64> %a, <vscale x 2 x i64> %b) {
; TRANSFORM-LABEL: test_adclb_s64:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z2, z0
; TRANSFORM-NEXT:    adclb z2.d, z0.d, z1.d
; TRANSFORM-NEXT:    adclb z2.d, z0.d, z1.d
; TRANSFORM-NEXT:    mov z0.d, z2.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_adclb_s64:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z2.d, z0.d
; NOTRANSFORM-NEXT:    adclb z2.d, z0.d, z1.d
; NOTRANSFORM-NEXT:    adclb z2.d, z0.d, z1.d
; NOTRANSFORM-NEXT:    mov z0.d, z2.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.adclb.nxv2i64(<vscale x 2 x i64> %a, <vscale x 2 x i64> %a, <vscale x 2 x i64> %b)
  %2 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.adclb.nxv2i64(<vscale x 2 x i64> %1, <vscale x 2 x i64> %a, <vscale x 2 x i64> %b)
  ret <vscale x 2 x i64> %2
}

define dso_local <vscale x 2 x i64> @test_adclt_s64(<vscale x 2 x i64> %a, <vscale x 2 x i64> %b) {
; TRANSFORM-LABEL: test_adclt_s64:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z2, z0
; TRANSFORM-NEXT:    adclt z2.d, z0.d, z1.d
; TRANSFORM-NEXT:    adclt z2.d, z0.d, z1.d
; TRANSFORM-NEXT:    mov z0.d, z2.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_adclt_s64:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z2.d, z0.d
; NOTRANSFORM-NEXT:    adclt z2.d, z0.d, z1.d
; NOTRANSFORM-NEXT:    adclt z2.d, z0.d, z1.d
; NOTRANSFORM-NEXT:    mov z0.d, z2.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.adclt.nxv2i64(<vscale x 2 x i64> %a, <vscale x 2 x i64> %a, <vscale x 2 x i64> %b)
  %2 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.adclt.nxv2i64(<vscale x 2 x i64> %1, <vscale x 2 x i64> %a, <vscale x 2 x i64> %b)
  ret <vscale x 2 x i64> %2
}

define dso_local <vscale x 2 x i64> @test_sbclb_s64(<vscale x 2 x i64> %a, <vscale x 2 x i64> %b) {
; TRANSFORM-LABEL: test_sbclb_s64:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z2, z0
; TRANSFORM-NEXT:    sbclb z2.d, z0.d, z1.d
; TRANSFORM-NEXT:    sbclb z2.d, z0.d, z1.d
; TRANSFORM-NEXT:    mov z0.d, z2.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_sbclb_s64:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z2.d, z0.d
; NOTRANSFORM-NEXT:    sbclb z2.d, z0.d, z1.d
; NOTRANSFORM-NEXT:    sbclb z2.d, z0.d, z1.d
; NOTRANSFORM-NEXT:    mov z0.d, z2.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.sbclb.nxv2i64(<vscale x 2 x i64> %a, <vscale x 2 x i64> %a, <vscale x 2 x i64> %b)
  %2 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.sbclb.nxv2i64(<vscale x 2 x i64> %1, <vscale x 2 x i64> %a, <vscale x 2 x i64> %b)
  ret <vscale x 2 x i64> %2
}

define dso_local <vscale x 2 x i64> @test_sbclt_s64(<vscale x 2 x i64> %a, <vscale x 2 x i64> %b) {
; TRANSFORM-LABEL: test_sbclt_s64:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z2, z0
; TRANSFORM-NEXT:    sbclt z2.d, z0.d, z1.d
; TRANSFORM-NEXT:    sbclt z2.d, z0.d, z1.d
; TRANSFORM-NEXT:    mov z0.d, z2.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_sbclt_s64:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z2.d, z0.d
; NOTRANSFORM-NEXT:    sbclt z2.d, z0.d, z1.d
; NOTRANSFORM-NEXT:    sbclt z2.d, z0.d, z1.d
; NOTRANSFORM-NEXT:    mov z0.d, z2.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.sbclt.nxv2i64(<vscale x 2 x i64> %a, <vscale x 2 x i64> %a, <vscale x 2 x i64> %b)
  %2 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.sbclt.nxv2i64(<vscale x 2 x i64> %1, <vscale x 2 x i64> %a, <vscale x 2 x i64> %b)
  ret <vscale x 2 x i64> %2
}

define dso_local <vscale x 4 x i32> @test_saba_s32(<vscale x 4 x i32> %a, <vscale x 4 x i32> %b) {
; TRANSFORM-LABEL: test_saba_s32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z2, z0
; TRANSFORM-NEXT:    saba z2.s, z0.s, z1.s
; TRANSFORM-NEXT:    saba z2.s, z0.s, z1.s
; TRANSFORM-NEXT:    mov z0.d, z2.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_saba_s32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z2.d, z0.d
; NOTRANSFORM-NEXT:    saba z2.s, z0.s, z1.s
; NOTRANSFORM-NEXT:    saba z2.s, z0.s, z1.s
; NOTRANSFORM-NEXT:    mov z0.d, z2.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.saba.nxv4i32(<vscale x 4 x i32> %a, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b)
  %2 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.saba.nxv4i32(<vscale x 4 x i32> %1, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b)
  ret <vscale x 4 x i32> %2
}

define dso_local <vscale x 4 x i32> @test_uaba_s32(<vscale x 4 x i32> %a, <vscale x 4 x i32> %b) {
; TRANSFORM-LABEL: test_uaba_s32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    mov z2.d, z0.d
; TRANSFORM-NEXT:    uaba z2.s, z0.s, z1.s
; TRANSFORM-NEXT:    uaba z2.s, z0.s, z1.s
; TRANSFORM-NEXT:    mov z0.d, z2.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_uaba_s32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z2.d, z0.d
; NOTRANSFORM-NEXT:    uaba z2.s, z0.s, z1.s
; NOTRANSFORM-NEXT:    uaba z2.s, z0.s, z1.s
; NOTRANSFORM-NEXT:    mov z0.d, z2.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.uaba.nxv4i32(<vscale x 4 x i32> %a, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b)
  %2 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.uaba.nxv4i32(<vscale x 4 x i32> %1, <vscale x 4 x i32> %a, <vscale x 4 x i32> %b)
  ret <vscale x 4 x i32> %2
}

define dso_local <vscale x 2 x i64> @test_sabalb_s64(<vscale x 4 x i32> %a, <vscale x 4 x i32> %b) {
; TRANSFORM-LABEL: test_sabalb_s64:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    sabalb z1.d, z0.s, z0.s
; TRANSFORM-NEXT:    sabalb z1.d, z0.s, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_sabalb_s64:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    sabalb z1.d, z0.s, z0.s
; NOTRANSFORM-NEXT:    sabalb z1.d, z0.s, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.sabalb.nxv2i64(<vscale x 2 x i64> poison, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  %2 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.sabalb.nxv2i64(<vscale x 2 x i64> %1, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  ret <vscale x 2 x i64> %2
}

define dso_local <vscale x 2 x i64> @test_sabalt_s64(<vscale x 4 x i32> %a, <vscale x 4 x i32> %b) {
; TRANSFORM-LABEL: test_sabalt_s64:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    sabalt z1.d, z0.s, z0.s
; TRANSFORM-NEXT:    sabalt z1.d, z0.s, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_sabalt_s64:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    sabalt z1.d, z0.s, z0.s
; NOTRANSFORM-NEXT:    sabalt z1.d, z0.s, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.sabalt.nxv2i64(<vscale x 2 x i64> poison, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  %2 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.sabalt.nxv2i64(<vscale x 2 x i64> %1, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  ret <vscale x 2 x i64> %2
}

define dso_local <vscale x 2 x i64> @test_uabalb_s64(<vscale x 4 x i32> %a, <vscale x 4 x i32> %b) {
; TRANSFORM-LABEL: test_uabalb_s64:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    uabalb z1.d, z0.s, z0.s
; TRANSFORM-NEXT:    uabalb z1.d, z0.s, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_uabalb_s64:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    uabalb z1.d, z0.s, z0.s
; NOTRANSFORM-NEXT:    uabalb z1.d, z0.s, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.uabalb.nxv2i64(<vscale x 2 x i64> poison, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  %2 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.uabalb.nxv2i64(<vscale x 2 x i64> %1, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  ret <vscale x 2 x i64> %2
}

define dso_local <vscale x 2 x i64> @test_uabalt_s64(<vscale x 4 x i32> %a, <vscale x 4 x i32> %b) {
; TRANSFORM-LABEL: test_uabalt_s64:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    uabalt z1.d, z0.s, z0.s
; TRANSFORM-NEXT:    uabalt z1.d, z0.s, z0.s
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_uabalt_s64:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    uabalt z1.d, z0.s, z0.s
; NOTRANSFORM-NEXT:    uabalt z1.d, z0.s, z0.s
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.uabalt.nxv2i64(<vscale x 2 x i64> poison, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  %2 = tail call <vscale x 2 x i64> @llvm.aarch64.sve.uabalt.nxv2i64(<vscale x 2 x i64> %1, <vscale x 4 x i32> %a, <vscale x 4 x i32> %a)
  ret <vscale x 2 x i64> %2
}

define dso_local <vscale x 4 x i32> @test_ssra_s32(<vscale x 4 x i32> %a) {
; TRANSFORM-LABEL: test_ssra_s32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    ssra z1.s, z0.s, #2
; TRANSFORM-NEXT:    ssra z1.s, z0.s, #2
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_ssra_s32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    ssra z1.s, z0.s, #2
; NOTRANSFORM-NEXT:    ssra z1.s, z0.s, #2
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.ssra.nxv4i32(<vscale x 4 x i32> %a, <vscale x 4 x i32> %a, i32 2)
  %2 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.ssra.nxv4i32(<vscale x 4 x i32> %1, <vscale x 4 x i32> %a, i32 2)
  ret <vscale x 4 x i32> %2
}

define dso_local <vscale x 4 x i32> @test_usra_s32(<vscale x 4 x i32> %a) {
; TRANSFORM-LABEL: test_usra_s32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    usra z1.s, z0.s, #2
; TRANSFORM-NEXT:    usra z1.s, z0.s, #2
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_usra_s32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    usra z1.s, z0.s, #2
; NOTRANSFORM-NEXT:    usra z1.s, z0.s, #2
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.usra.nxv4i32(<vscale x 4 x i32> %a, <vscale x 4 x i32> %a, i32 2)
  %2 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.usra.nxv4i32(<vscale x 4 x i32> %1, <vscale x 4 x i32> %a, i32 2)
  ret <vscale x 4 x i32> %2
}

define dso_local <vscale x 4 x i32> @test_srsra_s32(<vscale x 4 x i32> %a) {
; TRANSFORM-LABEL: test_srsra_s32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    srsra z1.s, z0.s, #2
; TRANSFORM-NEXT:    srsra z1.s, z0.s, #2
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_srsra_s32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    srsra z1.s, z0.s, #2
; NOTRANSFORM-NEXT:    srsra z1.s, z0.s, #2
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.srsra.nxv4i32(<vscale x 4 x i32> %a, <vscale x 4 x i32> %a, i32 2)
  %2 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.srsra.nxv4i32(<vscale x 4 x i32> %1, <vscale x 4 x i32> %a, i32 2)
  ret <vscale x 4 x i32> %2
}

define dso_local <vscale x 4 x i32> @test_ursra_s32(<vscale x 4 x i32> %a) {
; TRANSFORM-LABEL: test_ursra_s32:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    movprfx z1, z0
; TRANSFORM-NEXT:    ursra z1.s, z0.s, #2
; TRANSFORM-NEXT:    ursra z1.s, z0.s, #2
; TRANSFORM-NEXT:    mov z0.d, z1.d
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_ursra_s32:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    ursra z1.s, z0.s, #2
; NOTRANSFORM-NEXT:    ursra z1.s, z0.s, #2
; NOTRANSFORM-NEXT:    mov z0.d, z1.d
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.ursra.nxv4i32(<vscale x 4 x i32> %a, <vscale x 4 x i32> %a, i32 2)
  %2 = tail call <vscale x 4 x i32> @llvm.aarch64.sve.ursra.nxv4i32(<vscale x 4 x i32> %1, <vscale x 4 x i32> %a, i32 2)
  ret <vscale x 4 x i32> %2
}

define dso_local <vscale x 16 x i8> @test_ext_i8(<vscale x 16 x i8> %a) {
; TRANSFORM-LABEL: test_ext_i8:
; TRANSFORM:       // %bb.0:
; TRANSFORM-NEXT:    // kill: def $z0 killed $z0 def $z31_z0_z1
; TRANSFORM-NEXT:    mov z1.d, z0.d
; TRANSFORM-NEXT:    ext z31.b, { z0.b, z1.b }, #4
; TRANSFORM-NEXT:    ext z0.b, { z31.b, z0.b }, #4
; TRANSFORM-NEXT:    ret
;
; NOTRANSFORM-LABEL: test_ext_i8:
; NOTRANSFORM:       // %bb.0:
; NOTRANSFORM-NEXT:    // kill: def $z0 killed $z0 def $z31_z0_z1
; NOTRANSFORM-NEXT:    mov z1.d, z0.d
; NOTRANSFORM-NEXT:    ext z31.b, { z0.b, z1.b }, #4
; NOTRANSFORM-NEXT:    ext z0.b, { z31.b, z0.b }, #4
; NOTRANSFORM-NEXT:    ret
  %1 = tail call <vscale x 16 x i8> @llvm.aarch64.sve.ext.nxv16i8(<vscale x 16 x i8> %a, <vscale x 16 x i8> %a, i32 4)
  %2 = tail call <vscale x 16 x i8> @llvm.aarch64.sve.ext.nxv16i8(<vscale x 16 x i8> %1, <vscale x 16 x i8> %a, i32 4)
  ret <vscale x 16 x i8> %2
}

;; ============================================================================
;; Intrinsic declarations
;; ============================================================================

declare <vscale x 16 x i8> @llvm.aarch64.sve.mad.nxv16i8(<vscale x 16 x i1>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>)
declare <vscale x 8 x i16> @llvm.aarch64.sve.mad.nxv8i16(<vscale x 8 x i1>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>)
declare <vscale x 4 x i32> @llvm.aarch64.sve.mad.nxv4i32(<vscale x 4 x i1>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 2 x i64> @llvm.aarch64.sve.mad.nxv2i64(<vscale x 2 x i1>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>)
declare <vscale x 16 x i8> @llvm.aarch64.sve.mla.nxv16i8(<vscale x 16 x i1>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>)
declare <vscale x 16 x i8> @llvm.aarch64.sve.mls.nxv16i8(<vscale x 16 x i1>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>)
declare <vscale x 8 x i16> @llvm.aarch64.sve.mls.nxv8i16(<vscale x 8 x i1>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>)
declare <vscale x 8 x half> @llvm.aarch64.sve.fmad.nxv8f16(<vscale x 8 x i1>, <vscale x 8 x half>, <vscale x 8 x half>, <vscale x 8 x half>)
declare <vscale x 4 x float> @llvm.aarch64.sve.fmad.nxv4f32(<vscale x 4 x i1>, <vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>)
declare <vscale x 2 x double> @llvm.aarch64.sve.fmad.nxv2f64(<vscale x 2 x i1>, <vscale x 2 x double>, <vscale x 2 x double>, <vscale x 2 x double>)
declare <vscale x 2 x double> @llvm.aarch64.sve.fsqrt.nxv2f64(<vscale x 2 x double>, <vscale x 2 x i1>, <vscale x 2 x double>)
declare <vscale x 4 x i32> @llvm.aarch64.sve.msb.nxv4i32(<vscale x 4 x i1>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 4 x float> @llvm.aarch64.sve.fmsb.nxv4f32(<vscale x 4 x i1>, <vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>)
declare <vscale x 4 x float> @llvm.aarch64.sve.fnmad.nxv4f32(<vscale x 4 x i1>, <vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>)
declare <vscale x 4 x float> @llvm.aarch64.sve.fnmsb.nxv4f32(<vscale x 4 x i1>, <vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>)
declare <vscale x 4 x float> @llvm.aarch64.sve.fcmla.nxv4f32(<vscale x 4 x i1>, <vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, i32)
declare <vscale x 4 x i32> @llvm.aarch64.sve.shadd.nxv4i32(<vscale x 4 x i1>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 4 x i32> @llvm.aarch64.sve.uhadd.nxv4i32(<vscale x 4 x i1>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 4 x i32> @llvm.aarch64.sve.shsub.nxv4i32(<vscale x 4 x i1>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 4 x i32> @llvm.aarch64.sve.uhsub.nxv4i32(<vscale x 4 x i1>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 4 x i32> @llvm.aarch64.sve.shsubr.nxv4i32(<vscale x 4 x i1>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 4 x i32> @llvm.aarch64.sve.uhsubr.nxv4i32(<vscale x 4 x i1>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 4 x i32> @llvm.aarch64.sve.srhadd.nxv4i32(<vscale x 4 x i1>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 4 x i32> @llvm.aarch64.sve.urhadd.nxv4i32(<vscale x 4 x i1>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 4 x i32> @llvm.aarch64.sve.sqadd.nxv4i32(<vscale x 4 x i1>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 4 x i32> @llvm.aarch64.sve.uqadd.nxv4i32(<vscale x 4 x i1>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 4 x i32> @llvm.aarch64.sve.sqsub.nxv4i32(<vscale x 4 x i1>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 4 x i32> @llvm.aarch64.sve.uqsub.nxv4i32(<vscale x 4 x i1>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 4 x i32> @llvm.aarch64.sve.suqadd.nxv4i32(<vscale x 4 x i1>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 4 x i32> @llvm.aarch64.sve.usqadd.nxv4i32(<vscale x 4 x i1>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 4 x i32> @llvm.aarch64.sve.sqsubr.nxv4i32(<vscale x 4 x i1>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 4 x i32> @llvm.aarch64.sve.uqsubr.nxv4i32(<vscale x 4 x i1>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 4 x i32> @llvm.aarch64.sve.addp.nxv4i32(<vscale x 4 x i1>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 2 x i64> @llvm.aarch64.sve.sadalp.nxv2i64(<vscale x 2 x i1>, <vscale x 2 x i64>, <vscale x 4 x i32>)
declare <vscale x 2 x i64> @llvm.aarch64.sve.uadalp.nxv2i64(<vscale x 2 x i1>, <vscale x 2 x i64>, <vscale x 4 x i32>)
declare <vscale x 4 x i32> @llvm.aarch64.sve.smaxp.nxv4i32(<vscale x 4 x i1>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 4 x i32> @llvm.aarch64.sve.umaxp.nxv4i32(<vscale x 4 x i1>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 4 x i32> @llvm.aarch64.sve.sminp.nxv4i32(<vscale x 4 x i1>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 4 x i32> @llvm.aarch64.sve.uminp.nxv4i32(<vscale x 4 x i1>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 4 x float> @llvm.aarch64.sve.fabd.nxv4f32(<vscale x 4 x i1>, <vscale x 4 x float>, <vscale x 4 x float>)
declare <vscale x 4 x float> @llvm.aarch64.sve.faddp.nxv4f32(<vscale x 4 x i1>, <vscale x 4 x float>, <vscale x 4 x float>)
declare <vscale x 4 x float> @llvm.aarch64.sve.fcadd.nxv4f32(<vscale x 4 x i1>, <vscale x 4 x float>, <vscale x 4 x float>, i32)
declare <vscale x 4 x float> @llvm.aarch64.sve.fmaxnmp.nxv4f32(<vscale x 4 x i1>, <vscale x 4 x float>, <vscale x 4 x float>)
declare <vscale x 4 x float> @llvm.aarch64.sve.fminnmp.nxv4f32(<vscale x 4 x i1>, <vscale x 4 x float>, <vscale x 4 x float>)
declare <vscale x 4 x float> @llvm.aarch64.sve.fmaxp.nxv4f32(<vscale x 4 x i1>, <vscale x 4 x float>, <vscale x 4 x float>)
declare <vscale x 4 x float> @llvm.aarch64.sve.fminp.nxv4f32(<vscale x 4 x i1>, <vscale x 4 x float>, <vscale x 4 x float>)
declare <vscale x 4 x float> @llvm.aarch64.sve.fscale.nxv4f32(<vscale x 4 x i1>, <vscale x 4 x float>, <vscale x 4 x i32>)
declare <vscale x 4 x float> @llvm.aarch64.sve.fmulx.nxv4f32(<vscale x 4 x i1>, <vscale x 4 x float>, <vscale x 4 x float>)
declare <vscale x 4 x i32> @llvm.aarch64.sve.sqabs.nxv4i32(<vscale x 4 x i32>, <vscale x 4 x i1>, <vscale x 4 x i32>)
declare <vscale x 4 x i32> @llvm.aarch64.sve.sqneg.nxv4i32(<vscale x 4 x i32>, <vscale x 4 x i1>, <vscale x 4 x i32>)
declare <vscale x 4 x i32> @llvm.aarch64.sve.bsl.nxv4i32(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 4 x i32> @llvm.aarch64.sve.bsl1n.nxv4i32(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 4 x i32> @llvm.aarch64.sve.bsl2n.nxv4i32(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 4 x i32> @llvm.aarch64.sve.nbsl.nxv4i32(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 4 x i32> @llvm.aarch64.sve.eor3.nxv4i32(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 4 x i32> @llvm.aarch64.sve.bcax.nxv4i32(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 4 x i32> @llvm.aarch64.sve.xar.nxv4i32(<vscale x 4 x i32>, <vscale x 4 x i32>, i32)
declare <vscale x 4 x i32> @llvm.aarch64.sve.sqrdmlah.nxv4i32(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 4 x i32> @llvm.aarch64.sve.sqrdmlsh.nxv4i32(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 2 x i64> @llvm.aarch64.sve.smlalb.nxv2i64(<vscale x 2 x i64>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 2 x i64> @llvm.aarch64.sve.smlalt.nxv2i64(<vscale x 2 x i64>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 2 x i64> @llvm.aarch64.sve.smlslb.nxv2i64(<vscale x 2 x i64>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 2 x i64> @llvm.aarch64.sve.smlslt.nxv2i64(<vscale x 2 x i64>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 2 x i64> @llvm.aarch64.sve.umlslb.nxv2i64(<vscale x 2 x i64>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 2 x i64> @llvm.aarch64.sve.umlslt.nxv2i64(<vscale x 2 x i64>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 2 x i64> @llvm.aarch64.sve.sqdmlalb.nxv2i64(<vscale x 2 x i64>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 2 x i64> @llvm.aarch64.sve.sqdmlalt.nxv2i64(<vscale x 2 x i64>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 2 x i64> @llvm.aarch64.sve.sqdmlslb.nxv2i64(<vscale x 2 x i64>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 2 x i64> @llvm.aarch64.sve.sqdmlslt.nxv2i64(<vscale x 2 x i64>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 2 x i64> @llvm.aarch64.sve.sqdmlalbt.nxv2i64(<vscale x 2 x i64>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 2 x i64> @llvm.aarch64.sve.sqdmlslbt.nxv2i64(<vscale x 2 x i64>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 2 x i64> @llvm.aarch64.sve.adclb.nxv2i64(<vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>)
declare <vscale x 2 x i64> @llvm.aarch64.sve.adclt.nxv2i64(<vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>)
declare <vscale x 2 x i64> @llvm.aarch64.sve.sbclb.nxv2i64(<vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>)
declare <vscale x 2 x i64> @llvm.aarch64.sve.sbclt.nxv2i64(<vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>)
declare <vscale x 4 x i32> @llvm.aarch64.sve.saba.nxv4i32(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 4 x i32> @llvm.aarch64.sve.uaba.nxv4i32(<vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 2 x i64> @llvm.aarch64.sve.sabalb.nxv2i64(<vscale x 2 x i64>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 2 x i64> @llvm.aarch64.sve.sabalt.nxv2i64(<vscale x 2 x i64>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 2 x i64> @llvm.aarch64.sve.uabalb.nxv2i64(<vscale x 2 x i64>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 2 x i64> @llvm.aarch64.sve.uabalt.nxv2i64(<vscale x 2 x i64>, <vscale x 4 x i32>, <vscale x 4 x i32>)
declare <vscale x 4 x i32> @llvm.aarch64.sve.ssra.nxv4i32(<vscale x 4 x i32>, <vscale x 4 x i32>, i32)
declare <vscale x 4 x i32> @llvm.aarch64.sve.usra.nxv4i32(<vscale x 4 x i32>, <vscale x 4 x i32>, i32)
declare <vscale x 4 x i32> @llvm.aarch64.sve.srsra.nxv4i32(<vscale x 4 x i32>, <vscale x 4 x i32>, i32)
declare <vscale x 4 x i32> @llvm.aarch64.sve.ursra.nxv4i32(<vscale x 4 x i32>, <vscale x 4 x i32>, i32)
declare <vscale x 16 x i8> @llvm.aarch64.sve.ext.nxv16i8(<vscale x 16 x i8>, <vscale x 16 x i8>, i32)
