//===----------------------------------------------------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// WARNING: This test was generated by generate_header_inclusion_tests.py
// and should not be edited manually.
//
// clang-format off

// UNSUPPORTED: c++03, c++11, c++14, c++17

// <coroutine>

// Test that <coroutine> includes all the other headers it's supposed to.

#include <coroutine>
#include "test_macros.h"

#if !defined(_LIBCUDACXX_COROUTINE)
 #   error "<coroutine> was expected to define _LIBCUDACXX_COROUTINE"
#endif
#if TEST_STD_VER > 17 && !defined(_LIBCUDACXX_COMPARE)
 #   error "<coroutine> should include <compare> in C++20 and later"
#endif
