; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -O2 -mtriple=aarch64-unknown-linux-gnu < %s 2>&1 | FileCheck %s --check-prefixes=CHECK-COMMON,CHECK-NO-HBC
; RUN: llc -O2 -mtriple=aarch64-unknown-linux-gnu \
; RUN:     --biased-branch-insts-profile=%S/Inputs/aarch64-hbc-biasedbranch.afdo < %s 2>&1 | FileCheck %s \
; RUN:     --check-prefixes=CHECK-COMMON,CHECK-HAS-HBC
; ModuleID = 'original.cpp'
source_filename = "original.cpp"
target datalayout = "e-m:e-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128"
target triple = "aarch64-unknown-linux-gnu"

; Function Attrs: mustprogress noinline nounwind optnone uwtable
define dso_local noundef i32 @_Z16CBZTransformTestm(i64 noundef %0) #0 !dbg !10 {
; CHECK-COMMON-LABEL: _Z16CBZTransformTestm:
; CHECK-COMMON:       .Lfunc_begin0:
; CHECK-COMMON-NEXT:    .file 1 "/home/w00882830/llvm-project" "original.cpp"
; CHECK-COMMON-NEXT:    .loc 1 2 0 // original.cpp:2:0
; CHECK-COMMON-NEXT:    .cfi_startproc
; CHECK-COMMON-NEXT:  // %bb.0:
; CHECK-COMMON-NEXT:    sub sp, sp, #16
; CHECK-COMMON-NEXT:    .cfi_def_cfa_offset 16
; CHECK-COMMON-NEXT:    str x0, [sp, #8]
; CHECK-COMMON-NEXT:  .Ltmp3:
; CHECK-COMMON-NEXT:    .loc 1 3 18 prologue_end // original.cpp:3:18
; CHECK-COMMON-NEXT:    str wzr, [sp, #4]
; CHECK-COMMON-NEXT:  .LBB0_1: // =>This Inner Loop Header: Depth=1
; CHECK-COMMON-NEXT:    .loc 1 4 12 // original.cpp:4:12
; CHECK-COMMON-NEXT:    ldr x8, [sp, #8]
; CHECK-COMMON-NEXT:    .loc 1 4 5 is_stmt 0 // original.cpp:4:5
; CHECK-NO-HBC-NEXT:    cbz x8, .LBB0_3
; CHECK-HAS-HBC-NEXT:    cmp x8, #0
; CHECK-HAS-HBC-NEXT:    bc.eq .LBB0_3
; CHECK-COMMON-NEXT:  // %bb.2: // in Loop: Header=BB0_1 Depth=1
; CHECK-COMMON-NEXT:  .Ltmp4:
; CHECK-COMMON-NEXT:    .loc 1 5 16 is_stmt 1 // original.cpp:5:16
; CHECK-COMMON-NEXT:    ldr x8, [sp, #8]
; CHECK-COMMON-NEXT:    .loc 1 5 21 is_stmt 0 // original.cpp:5:21
; CHECK-COMMON-NEXT:    and x8, x8, #0x1
; CHECK-COMMON-NEXT:    .loc 1 5 13 // original.cpp:5:13
; CHECK-COMMON-NEXT:    ldr w9, [sp, #4]
; CHECK-COMMON-NEXT:    add x8, x9, x8
; CHECK-COMMON-NEXT:    str w8, [sp, #4]
; CHECK-COMMON-NEXT:    .loc 1 6 16 is_stmt 1 // original.cpp:6:16
; CHECK-COMMON-NEXT:    ldr x8, [sp, #8]
; CHECK-COMMON-NEXT:    .loc 1 6 21 is_stmt 0 // original.cpp:6:21
; CHECK-COMMON-NEXT:    lsr x8, x8, #1
; CHECK-COMMON-NEXT:    .loc 1 6 14 // original.cpp:6:14
; CHECK-COMMON-NEXT:    str x8, [sp, #8]
; CHECK-COMMON-NEXT:  .Ltmp5:
; CHECK-COMMON-NEXT:    .loc 1 4 5 is_stmt 1 // original.cpp:4:5
; CHECK-COMMON-NEXT:    b .LBB0_1
; CHECK-COMMON-NEXT:  .LBB0_3:
; CHECK-COMMON-NEXT:    .loc 1 8 12 // original.cpp:8:12
; CHECK-COMMON-NEXT:    ldr w0, [sp, #4]
; CHECK-COMMON-NEXT:    .loc 1 8 5 epilogue_begin is_stmt 0 // original.cpp:8:5
; CHECK-COMMON-NEXT:    add sp, sp, #16
; CHECK-COMMON-NEXT:    .cfi_def_cfa_offset 0
; CHECK-COMMON-NEXT:    ret
; CHECK-COMMON-NEXT:  .Ltmp6:
  %2 = alloca i64, align 8
  %3 = alloca i32, align 4
  store i64 %0, ptr %2, align 8
  call void @llvm.dbg.declare(metadata ptr %2, metadata !16, metadata !DIExpression()), !dbg !17
  call void @llvm.dbg.declare(metadata ptr %3, metadata !18, metadata !DIExpression()), !dbg !19
  store i32 0, ptr %3, align 4, !dbg !19
  br label %4, !dbg !20

4:                                                ; preds = %7, %1
  %5 = load i64, ptr %2, align 8, !dbg !21
  %6 = icmp ne i64 %5, 0, !dbg !21
  br i1 %6, label %7, label %16, !dbg !20

7:                                                ; preds = %4
  %8 = load i64, ptr %2, align 8, !dbg !22
  %9 = and i64 %8, 1, !dbg !24
  %10 = load i32, ptr %3, align 4, !dbg !25
  %11 = zext i32 %10 to i64, !dbg !25
  %12 = add i64 %11, %9, !dbg !25
  %13 = trunc i64 %12 to i32, !dbg !25
  store i32 %13, ptr %3, align 4, !dbg !25
  %14 = load i64, ptr %2, align 8, !dbg !26
  %15 = lshr i64 %14, 1, !dbg !27
  store i64 %15, ptr %2, align 8, !dbg !28
  br label %4, !dbg !20, !llvm.loop !29

16:                                               ; preds = %4
  %17 = load i32, ptr %3, align 4, !dbg !32
  ret i32 %17, !dbg !33
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare void @llvm.dbg.declare(metadata, metadata, metadata) #1

; Function Attrs: mustprogress noinline nounwind optnone uwtable
define dso_local noundef i32 @_Z17CBNZTransformTestm(i64 noundef %0) #0 !dbg !34 {
; CHECK-COMMON-LABEL: _Z17CBNZTransformTestm:
; CHECK-COMMON:       .Lfunc_begin1:
; CHECK-COMMON-NEXT:    .loc 1 12 0 is_stmt 1 // original.cpp:12:0
; CHECK-COMMON-NEXT:    .cfi_startproc
; CHECK-COMMON-NEXT:  // %bb.0:
; CHECK-COMMON-NEXT:    sub sp, sp, #16
; CHECK-COMMON-NEXT:    .cfi_def_cfa_offset 16
; CHECK-COMMON-NEXT:    str x0, [sp, #8]
; CHECK-COMMON-NEXT:  .Ltmp7:
; CHECK-COMMON-NEXT:    .loc 1 13 18 prologue_end // original.cpp:13:18
; CHECK-COMMON-NEXT:    str wzr, [sp, #4]
; CHECK-COMMON-NEXT:  .LBB1_1: // =>This Inner Loop Header: Depth=1
; CHECK-COMMON-NEXT:  .Ltmp8:
; CHECK-COMMON-NEXT:    .loc 1 15 16 // original.cpp:15:16
; CHECK-COMMON-NEXT:    ldr x8, [sp, #8]
; CHECK-COMMON-NEXT:    .loc 1 15 21 is_stmt 0 // original.cpp:15:21
; CHECK-COMMON-NEXT:    and x8, x8, #0x1
; CHECK-COMMON-NEXT:    .loc 1 15 13 // original.cpp:15:13
; CHECK-COMMON-NEXT:    ldr w9, [sp, #4]
; CHECK-COMMON-NEXT:    add x8, x9, x8
; CHECK-COMMON-NEXT:    str w8, [sp, #4]
; CHECK-COMMON-NEXT:    .loc 1 16 16 is_stmt 1 // original.cpp:16:16
; CHECK-COMMON-NEXT:    ldr x8, [sp, #8]
; CHECK-COMMON-NEXT:    .loc 1 16 21 is_stmt 0 // original.cpp:16:21
; CHECK-COMMON-NEXT:    lsr x8, x8, #1
; CHECK-COMMON-NEXT:    .loc 1 16 14 // original.cpp:16:14
; CHECK-COMMON-NEXT:    str x8, [sp, #8]
; CHECK-COMMON-NEXT:  .Ltmp9:
; CHECK-COMMON-NEXT:  // %bb.2: // in Loop: Header=BB1_1 Depth=1
; CHECK-COMMON-NEXT:    .loc 1 17 14 is_stmt 1 // original.cpp:17:14
; CHECK-COMMON-NEXT:    ldr x8, [sp, #8]
; CHECK-COMMON-NEXT:  .Ltmp10:
; CHECK-COMMON-NEXT:    .loc 1 17 5 is_stmt 0 // original.cpp:17:5
; CHECK-NO-HBC-NEXT:    cbnz x8, .LBB1_1
; CHECK-HAS-HBC-NEXT:    cmp x8, #0
; CHECK-HAS-HBC-NEXT:    bc.ne .LBB1_1
; CHECK-COMMON-NEXT:  .Ltmp11:
; CHECK-COMMON-NEXT:  // %bb.3:
; CHECK-COMMON-NEXT:    .loc 1 18 12 is_stmt 1 // original.cpp:18:12
; CHECK-COMMON-NEXT:    ldr w0, [sp, #4]
; CHECK-COMMON-NEXT:    .loc 1 18 5 epilogue_begin is_stmt 0 // original.cpp:18:5
; CHECK-COMMON-NEXT:    add sp, sp, #16
; CHECK-COMMON-NEXT:    .cfi_def_cfa_offset 0
; CHECK-COMMON-NEXT:    ret
; CHECK-COMMON-NEXT:  .Ltmp12:
  %2 = alloca i64, align 8
  %3 = alloca i32, align 4
  store i64 %0, ptr %2, align 8
  call void @llvm.dbg.declare(metadata ptr %2, metadata !35, metadata !DIExpression()), !dbg !36
  call void @llvm.dbg.declare(metadata ptr %3, metadata !37, metadata !DIExpression()), !dbg !38
  store i32 0, ptr %3, align 4, !dbg !38
  br label %4, !dbg !39

4:                                                ; preds = %13, %1
  %5 = load i64, ptr %2, align 8, !dbg !40
  %6 = and i64 %5, 1, !dbg !42
  %7 = load i32, ptr %3, align 4, !dbg !43
  %8 = zext i32 %7 to i64, !dbg !43
  %9 = add i64 %8, %6, !dbg !43
  %10 = trunc i64 %9 to i32, !dbg !43
  store i32 %10, ptr %3, align 4, !dbg !43
  %11 = load i64, ptr %2, align 8, !dbg !44
  %12 = lshr i64 %11, 1, !dbg !45
  store i64 %12, ptr %2, align 8, !dbg !46
  br label %13, !dbg !47

13:                                               ; preds = %4
  %14 = load i64, ptr %2, align 8, !dbg !48
  %15 = icmp ne i64 %14, 0, !dbg !48
  br i1 %15, label %4, label %16, !dbg !47, !llvm.loop !49

16:                                               ; preds = %13
  %17 = load i32, ptr %3, align 4, !dbg !51
  ret i32 %17, !dbg !52
}

; Function Attrs: mustprogress noinline nounwind optnone uwtable
define dso_local noundef i32 @_Z18BcondTransformTestm(i64 noundef %0) #0 !dbg !53 {
; CHECK-COMMON-LABEL: _Z18BcondTransformTestm:
; CHECK-COMMON:       .Lfunc_begin2:
; CHECK-COMMON-NEXT:    .loc 1 22 0 is_stmt 1 // original.cpp:22:0
; CHECK-COMMON-NEXT:    .cfi_startproc
; CHECK-COMMON-NEXT:  // %bb.0:
; CHECK-COMMON-NEXT:    sub sp, sp, #16
; CHECK-COMMON-NEXT:    .cfi_def_cfa_offset 16
; CHECK-COMMON-NEXT:    str x0, [sp, #8]
; CHECK-COMMON-NEXT:  .Ltmp13:
; CHECK-COMMON-NEXT:    .loc 1 23 18 prologue_end // original.cpp:23:18
; CHECK-COMMON-NEXT:    str wzr, [sp, #4]
; CHECK-COMMON-NEXT:  .LBB2_1: // =>This Inner Loop Header: Depth=1
; CHECK-COMMON-NEXT:  .Ltmp14:
; CHECK-COMMON-NEXT:    .loc 1 25 16 // original.cpp:25:16
; CHECK-COMMON-NEXT:    ldr x8, [sp, #8]
; CHECK-COMMON-NEXT:    .loc 1 25 21 is_stmt 0 // original.cpp:25:21
; CHECK-COMMON-NEXT:    and x8, x8, #0x1
; CHECK-COMMON-NEXT:    .loc 1 25 13 // original.cpp:25:13
; CHECK-COMMON-NEXT:    ldr w9, [sp, #4]
; CHECK-COMMON-NEXT:    add x8, x9, x8
; CHECK-COMMON-NEXT:    str w8, [sp, #4]
; CHECK-COMMON-NEXT:    .loc 1 26 16 is_stmt 1 // original.cpp:26:16
; CHECK-COMMON-NEXT:    ldr x8, [sp, #8]
; CHECK-COMMON-NEXT:    .loc 1 26 21 is_stmt 0 // original.cpp:26:21
; CHECK-COMMON-NEXT:    lsr x8, x8, #1
; CHECK-COMMON-NEXT:    .loc 1 26 14 // original.cpp:26:14
; CHECK-COMMON-NEXT:    str x8, [sp, #8]
; CHECK-COMMON-NEXT:  .Ltmp15:
; CHECK-COMMON-NEXT:  // %bb.2: // in Loop: Header=BB2_1 Depth=1
; CHECK-COMMON-NEXT:    .loc 1 27 14 is_stmt 1 // original.cpp:27:14
; CHECK-COMMON-NEXT:    ldr x8, [sp, #8]
; CHECK-COMMON-NEXT:  .Ltmp16:
; CHECK-COMMON-NEXT:    .loc 1 27 5 is_stmt 0 // original.cpp:27:5
; CHECK-COMMON-NEXT:    cmp x8, #0
; CHECK-NO-HBC-NEXT:    b.hi .LBB2_1
; CHECK-HAS-HBC-NEXT:    bc.hi .LBB2_1
; CHECK-COMMON-NEXT:  .Ltmp17:
; CHECK-COMMON-NEXT:  // %bb.3:
; CHECK-COMMON-NEXT:    .loc 1 28 12 is_stmt 1 // original.cpp:28:12
; CHECK-COMMON-NEXT:    ldr w0, [sp, #4]
; CHECK-COMMON-NEXT:    .loc 1 28 5 epilogue_begin is_stmt 0 // original.cpp:28:5
; CHECK-COMMON-NEXT:    add sp, sp, #16
; CHECK-COMMON-NEXT:    .cfi_def_cfa_offset 0
; CHECK-COMMON-NEXT:    ret
; CHECK-COMMON-NEXT:  .Ltmp18:
  %2 = alloca i64, align 8
  %3 = alloca i32, align 4
  store i64 %0, ptr %2, align 8
  call void @llvm.dbg.declare(metadata ptr %2, metadata !54, metadata !DIExpression()), !dbg !55
  call void @llvm.dbg.declare(metadata ptr %3, metadata !56, metadata !DIExpression()), !dbg !57
  store i32 0, ptr %3, align 4, !dbg !57
  br label %4, !dbg !58

4:                                                ; preds = %13, %1
  %5 = load i64, ptr %2, align 8, !dbg !59
  %6 = and i64 %5, 1, !dbg !61
  %7 = load i32, ptr %3, align 4, !dbg !62
  %8 = zext i32 %7 to i64, !dbg !62
  %9 = add i64 %8, %6, !dbg !62
  %10 = trunc i64 %9 to i32, !dbg !62
  store i32 %10, ptr %3, align 4, !dbg !62
  %11 = load i64, ptr %2, align 8, !dbg !63
  %12 = lshr i64 %11, 1, !dbg !64
  store i64 %12, ptr %2, align 8, !dbg !65
  br label %13, !dbg !66

13:                                               ; preds = %4
  %14 = load i64, ptr %2, align 8, !dbg !67
  %15 = icmp ugt i64 %14, 0, !dbg !68
  br i1 %15, label %4, label %16, !dbg !66, !llvm.loop !69

16:                                               ; preds = %13
  %17 = load i32, ptr %3, align 4, !dbg !71
  ret i32 %17, !dbg !72
}

attributes #0 = { mustprogress noinline nounwind optnone uwtable "frame-pointer"="non-leaf" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="generic" "target-features"="+bf16,+crc,+dotprod,+fp-armv8,+hbc,+i8mm,+mops,+neon,+ras,+rcpc,+rdm,+v8.1a,+v8.2a,+v8.3a,+v8.4a,+v8.5a,+v8.6a,+v8.7a,+v8.8a,+v8a,-fmv" }
attributes #1 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!2, !3, !4, !5, !6, !7, !8}
!llvm.ident = !{!9}

!0 = distinct !DICompileUnit(language: DW_LANG_C_plus_plus_14, file: !1, producer: "clang version 17.0.6", isOptimized: false, runtimeVersion: 0, emissionKind: FullDebug, splitDebugInlining: false, nameTableKind: None)
!1 = !DIFile(filename: "original.cpp", directory: "/home/w00882830/llvm-project")
!2 = !{i32 7, !"Dwarf Version", i32 4}
!3 = !{i32 2, !"Debug Info Version", i32 3}
!4 = !{i32 1, !"wchar_size", i32 4}
!5 = !{i32 8, !"PIC Level", i32 2}
!6 = !{i32 7, !"PIE Level", i32 2}
!7 = !{i32 7, !"uwtable", i32 2}
!8 = !{i32 7, !"frame-pointer", i32 1}
!9 = !{!"clang version 17.0.6"}
!10 = distinct !DISubprogram(name: "CBZTransformTest", linkageName: "_Z16CBZTransformTestm", scope: !1, file: !1, line: 1, type: !11, scopeLine: 2, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !0, retainedNodes: !15)
!11 = !DISubroutineType(types: !12)
!12 = !{!13, !14}
!13 = !DIBasicType(name: "unsigned int", size: 32, encoding: DW_ATE_unsigned)
!14 = !DIBasicType(name: "unsigned long", size: 64, encoding: DW_ATE_unsigned)
!15 = !{}
!16 = !DILocalVariable(name: "_bit", arg: 1, scope: !10, file: !1, line: 1, type: !14)
!17 = !DILocation(line: 1, column: 45, scope: !10)
!18 = !DILocalVariable(name: "cnt", scope: !10, file: !1, line: 3, type: !13)
!19 = !DILocation(line: 3, column: 18, scope: !10)
!20 = !DILocation(line: 4, column: 5, scope: !10)
!21 = !DILocation(line: 4, column: 12, scope: !10)
!22 = !DILocation(line: 5, column: 16, scope: !23)
!23 = distinct !DILexicalBlock(scope: !10, file: !1, line: 4, column: 18)
!24 = !DILocation(line: 5, column: 21, scope: !23)
!25 = !DILocation(line: 5, column: 13, scope: !23)
!26 = !DILocation(line: 6, column: 16, scope: !23)
!27 = !DILocation(line: 6, column: 21, scope: !23)
!28 = !DILocation(line: 6, column: 14, scope: !23)
!29 = distinct !{!29, !20, !30, !31}
!30 = !DILocation(line: 7, column: 5, scope: !10)
!31 = !{!"llvm.loop.mustprogress"}
!32 = !DILocation(line: 8, column: 12, scope: !10)
!33 = !DILocation(line: 8, column: 5, scope: !10)
!34 = distinct !DISubprogram(name: "CBNZTransformTest", linkageName: "_Z17CBNZTransformTestm", scope: !1, file: !1, line: 11, type: !11, scopeLine: 12, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !0, retainedNodes: !15)
!35 = !DILocalVariable(name: "_bit", arg: 1, scope: !34, file: !1, line: 11, type: !14)
!36 = !DILocation(line: 11, column: 46, scope: !34)
!37 = !DILocalVariable(name: "cnt", scope: !34, file: !1, line: 13, type: !13)
!38 = !DILocation(line: 13, column: 18, scope: !34)
!39 = !DILocation(line: 14, column: 5, scope: !34)
!40 = !DILocation(line: 15, column: 16, scope: !41)
!41 = distinct !DILexicalBlock(scope: !34, file: !1, line: 14, column: 8)
!42 = !DILocation(line: 15, column: 21, scope: !41)
!43 = !DILocation(line: 15, column: 13, scope: !41)
!44 = !DILocation(line: 16, column: 16, scope: !41)
!45 = !DILocation(line: 16, column: 21, scope: !41)
!46 = !DILocation(line: 16, column: 14, scope: !41)
!47 = !DILocation(line: 17, column: 5, scope: !41)
!48 = !DILocation(line: 17, column: 14, scope: !34)
!49 = distinct !{!49, !39, !50, !31}
!50 = !DILocation(line: 17, column: 18, scope: !34)
!51 = !DILocation(line: 18, column: 12, scope: !34)
!52 = !DILocation(line: 18, column: 5, scope: !34)
!53 = distinct !DISubprogram(name: "BcondTransformTest", linkageName: "_Z18BcondTransformTestm", scope: !1, file: !1, line: 21, type: !11, scopeLine: 22, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !0, retainedNodes: !15)
!54 = !DILocalVariable(name: "_bit", arg: 1, scope: !53, file: !1, line: 21, type: !14)
!55 = !DILocation(line: 21, column: 47, scope: !53)
!56 = !DILocalVariable(name: "cnt", scope: !53, file: !1, line: 23, type: !13)
!57 = !DILocation(line: 23, column: 18, scope: !53)
!58 = !DILocation(line: 24, column: 5, scope: !53)
!59 = !DILocation(line: 25, column: 16, scope: !60)
!60 = distinct !DILexicalBlock(scope: !53, file: !1, line: 24, column: 8)
!61 = !DILocation(line: 25, column: 21, scope: !60)
!62 = !DILocation(line: 25, column: 13, scope: !60)
!63 = !DILocation(line: 26, column: 16, scope: !60)
!64 = !DILocation(line: 26, column: 21, scope: !60)
!65 = !DILocation(line: 26, column: 14, scope: !60)
!66 = !DILocation(line: 27, column: 5, scope: !60)
!67 = !DILocation(line: 27, column: 14, scope: !53)
!68 = !DILocation(line: 27, column: 19, scope: !53)
!69 = distinct !{!69, !58, !70, !31}
!70 = !DILocation(line: 27, column: 22, scope: !53)
!71 = !DILocation(line: 28, column: 12, scope: !53)
!72 = !DILocation(line: 28, column: 5, scope: !53)
