; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=loop-vectorize -enable-interleaved-mem-accesses=true -max-interleave-group-factor=16  -S < %s | FileCheck %s

define dso_local void @interleavedstore_16(ptr noalias noundef readonly %in, ptr noalias noundef writeonly  %out) {
; CHECK-LABEL: define dso_local void @interleavedstore_16(
; CHECK-SAME: ptr noalias noundef readonly [[IN:%.*]], ptr noalias noundef writeonly [[OUT:%.*]]) {
; CHECK:       vector.body:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %vector.ph ], [ [[INDEX_NEXT:%.*]], %vector.body ]
; CHECK-NEXT:    [[OFFSET_IDX:%.*]] = add i64 [[INDEX]], 0
; CHECK-NEXT:    [[TMP27:%.*]] = mul i64 [[OFFSET_IDX]], 16
; CHECK-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[OUT]], i64 [[TMP27]]
; CHECK-NEXT:    [[TMP28:%.*]] = add i64 [[INDEX]], 0
; CHECK-NEXT:    [[OFFSET_IDX2:%.*]] = mul i64 [[TMP28]], 4
; CHECK-NEXT:    [[NEXT_GEP6:%.*]] = getelementptr i8, ptr [[IN]], i64 [[OFFSET_IDX2]]
; CHECK-NEXT:    [[TMP29:%.*]] = getelementptr inbounds i8, ptr [[NEXT_GEP6]], i64 3
; CHECK-NEXT:    [[TMP30:%.*]] = getelementptr inbounds i8, ptr [[TMP29]], i32 -3
; CHECK-NEXT:    [[WIDE_VEC:%.*]] = load <16 x i8>, ptr [[TMP30]], align 1
; CHECK-NEXT:    [[STRIDED_VEC:%.*]] = shufflevector <16 x i8> [[WIDE_VEC]], <16 x i8> poison, <4 x i32> <i32 0, i32 4, i32 8, i32 12>
; CHECK-NEXT:    [[STRIDED_VEC4:%.*]] = shufflevector <16 x i8> [[WIDE_VEC]], <16 x i8> poison, <4 x i32> <i32 1, i32 5, i32 9, i32 13>
; CHECK-NEXT:    [[STRIDED_VEC5:%.*]] = shufflevector <16 x i8> [[WIDE_VEC]], <16 x i8> poison, <4 x i32> <i32 2, i32 6, i32 10, i32 14>
; CHECK-NEXT:    [[STRIDED_VEC6:%.*]] = shufflevector <16 x i8> [[WIDE_VEC]], <16 x i8> poison, <4 x i32> <i32 3, i32 7, i32 11, i32 15>
; CHECK-NEXT:    [[TMP0:%.*]] = add <4 x i8> [[STRIDED_VEC6]], [[STRIDED_VEC5]]
; CHECK-NEXT:    [[TMP1:%.*]] = add <4 x i8> [[STRIDED_VEC6]], [[STRIDED_VEC4]]
; CHECK-NEXT:    [[TMP2:%.*]] = add <4 x i8> [[STRIDED_VEC5]], [[STRIDED_VEC4]]
; CHECK-NEXT:    [[TMP3:%.*]] = add <4 x i8> [[STRIDED_VEC6]], [[TMP2]]
; CHECK-NEXT:    [[TMP4:%.*]] = add <4 x i8> [[STRIDED_VEC6]], [[STRIDED_VEC]]
; CHECK-NEXT:    [[TMP5:%.*]] = add <4 x i8> [[STRIDED_VEC5]], [[STRIDED_VEC]]
; CHECK-NEXT:    [[TMP6:%.*]] = add <4 x i8> [[STRIDED_VEC6]], [[TMP5]]
; CHECK-NEXT:    [[TMP7:%.*]] = add <4 x i8> [[STRIDED_VEC4]], [[STRIDED_VEC]]
; CHECK-NEXT:    [[TMP8:%.*]] = add <4 x i8> [[STRIDED_VEC6]], [[TMP7]]
; CHECK-NEXT:    [[TMP9:%.*]] = add <4 x i8> [[STRIDED_VEC5]], [[TMP7]]
; CHECK-NEXT:    [[TMP10:%.*]] = add <4 x i8> [[STRIDED_VEC6]], [[TMP9]]
; CHECK-NEXT:    [[TMP31:%.*]] = getelementptr inbounds i8, ptr [[NEXT_GEP]], i64 15
; CHECK-NEXT:    [[TMP32:%.*]] = getelementptr inbounds i8, ptr [[TMP31]], i32 -15
; CHECK-NEXT:    [[TMP11:%.*]] = shufflevector <4 x i8> zeroinitializer, <4 x i8> [[STRIDED_VEC6]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP12:%.*]] = shufflevector <4 x i8> [[STRIDED_VEC5]], <4 x i8> [[TMP0]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP13:%.*]] = shufflevector <4 x i8> [[STRIDED_VEC4]], <4 x i8> [[TMP1]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP14:%.*]] = shufflevector <4 x i8> [[TMP2]], <4 x i8> [[TMP3]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP15:%.*]] = shufflevector <4 x i8> [[STRIDED_VEC]], <4 x i8> [[TMP4]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP16:%.*]] = shufflevector <4 x i8> [[TMP5]], <4 x i8> [[TMP6]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP17:%.*]] = shufflevector <4 x i8> [[TMP7]], <4 x i8> [[TMP8]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP18:%.*]] = shufflevector <4 x i8> [[TMP9]], <4 x i8> [[TMP10]], <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
; CHECK-NEXT:    [[TMP19:%.*]] = shufflevector <8 x i8> [[TMP11]], <8 x i8> [[TMP12]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[TMP20:%.*]] = shufflevector <8 x i8> [[TMP13]], <8 x i8> [[TMP14]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[TMP21:%.*]] = shufflevector <8 x i8> [[TMP15]], <8 x i8> [[TMP16]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[TMP22:%.*]] = shufflevector <8 x i8> [[TMP17]], <8 x i8> [[TMP18]], <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
; CHECK-NEXT:    [[TMP23:%.*]] = shufflevector <16 x i8> [[TMP19]], <16 x i8> [[TMP20]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
; CHECK-NEXT:    [[TMP24:%.*]] = shufflevector <16 x i8> [[TMP21]], <16 x i8> [[TMP22]], <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
; CHECK-NEXT:    [[TMP25:%.*]] = shufflevector <32 x i8> [[TMP23]], <32 x i8> [[TMP24]], <64 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31, i32 32, i32 33, i32 34, i32 35, i32 36, i32 37, i32 38, i32 39, i32 40, i32 41, i32 42, i32 43, i32 44, i32 45, i32 46, i32 47, i32 48, i32 49, i32 50, i32 51, i32 52, i32 53, i32 54, i32 55, i32 56, i32 57, i32 58, i32 59, i32 60, i32 61, i32 62, i32 63>
; CHECK-NEXT:    [[INTERLEAVED_VEC:%.*]] = shufflevector <64 x i8> [[TMP25]], <64 x i8> poison, <64 x i32> <i32 0, i32 4, i32 8, i32 12, i32 16, i32 20, i32 24, i32 28, i32 32, i32 36, i32 40, i32 44, i32 48, i32 52, i32 56, i32 60, i32 1, i32 5, i32 9, i32 13, i32 17, i32 21, i32 25, i32 29, i32 33, i32 37, i32 41, i32 45, i32 49, i32 53, i32 57, i32 61, i32 2, i32 6, i32 10, i32 14, i32 18, i32 22, i32 26, i32 30, i32 34, i32 38, i32 42, i32 46, i32 50, i32 54, i32 58, i32 62, i32 3, i32 7, i32 11, i32 15, i32 19, i32 23, i32 27, i32 31, i32 35, i32 39, i32 43, i32 47, i32 51, i32 55, i32 59, i32 63>
; CHECK-NEXT:    store <64 x i8> [[INTERLEAVED_VEC]], ptr [[TMP32]], align 1
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 4
; CHECK-NEXT:    [[TMP26:%.*]] = icmp eq i64 [[INDEX_NEXT]], 32
; CHECK-NEXT:    br i1 [[TMP26]], label %[[MIDDLE_BLOCK:.*]], label %vector.body, !llvm.loop [[LOOP0:![0-9]+]]
entry:
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  ret void

for.body:                                         ; preds = %entry, %for.body
  %i.033 = phi i32 [ 0, %entry ], [ %inc17, %for.body ]
  %out.addr.032 = phi ptr [ %out, %entry ], [ %add.ptr, %for.body ]
  %in.addr.031 = phi ptr [ %in, %entry ], [ %add.ptr15, %for.body ]
  store i8 0, ptr %out.addr.032, align 1
  %arrayidx10 = getelementptr inbounds i8, ptr %in.addr.031, i64 3
  %0 = load i8, ptr %arrayidx10, align 1
  %arrayidx14 = getelementptr inbounds i8, ptr %out.addr.032, i64 1
  store i8 %0, ptr %arrayidx14, align 1
  %arrayidx10.1 = getelementptr inbounds i8, ptr %in.addr.031, i64 2
  %1 = load i8, ptr %arrayidx10.1, align 1
  %arrayidx14.1 = getelementptr inbounds i8, ptr %out.addr.032, i64 2
  store i8 %1, ptr %arrayidx14.1, align 1
  %add.2 = add i8 %0, %1
  %arrayidx14.2 = getelementptr inbounds i8, ptr %out.addr.032, i64 3
  store i8 %add.2, ptr %arrayidx14.2, align 1
  %arrayidx10.3 = getelementptr inbounds i8, ptr %in.addr.031, i64 1
  %2 = load i8, ptr %arrayidx10.3, align 1
  %arrayidx14.3 = getelementptr inbounds i8, ptr %out.addr.032, i64 4
  store i8 %2, ptr %arrayidx14.3, align 1
  %add.4 = add i8 %0, %2
  %arrayidx14.4 = getelementptr inbounds i8, ptr %out.addr.032, i64 5
  store i8 %add.4, ptr %arrayidx14.4, align 1
  %add.5 = add i8 %1, %2
  %arrayidx14.5 = getelementptr inbounds i8, ptr %out.addr.032, i64 6
  store i8 %add.5, ptr %arrayidx14.5, align 1
  %add.6 = add i8 %0, %add.5
  %arrayidx14.6 = getelementptr inbounds i8, ptr %out.addr.032, i64 7
  store i8 %add.6, ptr %arrayidx14.6, align 1
  %3 = load i8, ptr %in.addr.031, align 1
  %arrayidx14.7 = getelementptr inbounds i8, ptr %out.addr.032, i64 8
  store i8 %3, ptr %arrayidx14.7, align 1
  %add.8 = add i8 %0, %3
  %arrayidx14.8 = getelementptr inbounds i8, ptr %out.addr.032, i64 9
  store i8 %add.8, ptr %arrayidx14.8, align 1
  %add.9 = add i8 %1, %3
  %arrayidx14.9 = getelementptr inbounds i8, ptr %out.addr.032, i64 10
  store i8 %add.9, ptr %arrayidx14.9, align 1
  %add.10 = add i8 %0, %add.9
  %arrayidx14.10 = getelementptr inbounds i8, ptr %out.addr.032, i64 11
  store i8 %add.10, ptr %arrayidx14.10, align 1
  %add.11 = add i8 %2, %3
  %arrayidx14.11 = getelementptr inbounds i8, ptr %out.addr.032, i64 12
  store i8 %add.11, ptr %arrayidx14.11, align 1
  %add.12 = add i8 %0, %add.11
  %arrayidx14.12 = getelementptr inbounds i8, ptr %out.addr.032, i64 13
  store i8 %add.12, ptr %arrayidx14.12, align 1
  %add.13 = add i8 %1, %add.11
  %arrayidx14.13 = getelementptr inbounds i8, ptr %out.addr.032, i64 14
  store i8 %add.13, ptr %arrayidx14.13, align 1
  %add.14 = add i8 %0, %add.13
  %arrayidx14.14 = getelementptr inbounds i8, ptr %out.addr.032, i64 15
  store i8 %add.14, ptr %arrayidx14.14, align 1
  %add.ptr = getelementptr inbounds i8, ptr %out.addr.032, i64 16
  %add.ptr15 = getelementptr inbounds i8, ptr %in.addr.031, i64 4
  %inc17 = add nuw nsw i32 %i.033, 1
  %exitcond.not = icmp eq i32 %inc17, 32
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body, !llvm.loop !0
}

define dso_local void @interleavedstore_invalid_type(ptr nocapture noundef readonly %pSrc, ptr nocapture noundef writeonly %pDst, i64 noundef %length) {
; CHECK-LABEL: define dso_local void @interleavedstore_invalid_type(
; CHECK-SAME: ptr nocapture noundef readonly [[PSRC:%.*]], ptr nocapture noundef writeonly [[PDST:%.*]], i64 noundef [[LENGTH:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[AND:%.*]] = and i64 [[LENGTH]], -8
; CHECK-NEXT:    [[CMP70_NOT:%.*]] = icmp eq i64 [[AND]], 0
; CHECK-NEXT:    br i1 [[CMP70_NOT]], label %[[FOR_END:.*]], label %[[FOR_BODY_PREHEADER:.*]]
; CHECK:       [[FOR_BODY_PREHEADER]]:
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[PSRC_ADDR_072:%.*]] = phi ptr [ [[INCDEC_PTR7:%.*]], %[[FOR_BODY]] ], [ [[PSRC]], %[[FOR_BODY_PREHEADER]] ]
; CHECK-NEXT:    [[I_071:%.*]] = phi i64 [ [[ADD42:%.*]], %[[FOR_BODY]] ], [ 0, %[[FOR_BODY_PREHEADER]] ]
; CHECK-NEXT:    [[INCDEC_PTR:%.*]] = getelementptr inbounds i8, ptr [[PSRC_ADDR_072]], i64 1
; CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[PSRC_ADDR_072]], align 1
; CHECK-NEXT:    [[CONV:%.*]] = zext i8 [[TMP0]] to i32
; CHECK-NEXT:    [[INCDEC_PTR1:%.*]] = getelementptr inbounds i8, ptr [[PSRC_ADDR_072]], i64 2
; CHECK-NEXT:    [[TMP1:%.*]] = load i8, ptr [[INCDEC_PTR]], align 1
; CHECK-NEXT:    [[CONV2:%.*]] = zext i8 [[TMP1]] to i32
; CHECK-NEXT:    [[INCDEC_PTR3:%.*]] = getelementptr inbounds i8, ptr [[PSRC_ADDR_072]], i64 3
; CHECK-NEXT:    [[TMP2:%.*]] = load i8, ptr [[INCDEC_PTR1]], align 1
; CHECK-NEXT:    [[CONV4:%.*]] = zext i8 [[TMP2]] to i32
; CHECK-NEXT:    [[INCDEC_PTR5:%.*]] = getelementptr inbounds i8, ptr [[PSRC_ADDR_072]], i64 4
; CHECK-NEXT:    [[TMP3:%.*]] = load i8, ptr [[INCDEC_PTR3]], align 1
; CHECK-NEXT:    [[CONV6:%.*]] = zext i8 [[TMP3]] to i32
; CHECK-NEXT:    [[INCDEC_PTR7]] = getelementptr inbounds i8, ptr [[PSRC_ADDR_072]], i64 5
; CHECK-NEXT:    [[TMP4:%.*]] = load i8, ptr [[INCDEC_PTR5]], align 1
; CHECK-NEXT:    [[CONV8:%.*]] = zext i8 [[TMP4]] to i32
; CHECK-NEXT:    [[SHR:%.*]] = lshr i32 [[CONV]], 3
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[PDST]], i64 [[I_071]]
; CHECK-NEXT:    store i32 [[SHR]], ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[AND9:%.*]] = shl nuw nsw i32 [[CONV]], 2
; CHECK-NEXT:    [[SHL:%.*]] = and i32 [[AND9]], 28
; CHECK-NEXT:    [[SHR10:%.*]] = lshr i32 [[CONV2]], 6
; CHECK-NEXT:    [[OR:%.*]] = or i32 [[SHL]], [[SHR10]]
; CHECK-NEXT:    [[ADD11:%.*]] = or i64 [[I_071]], 1
; CHECK-NEXT:    [[ARRAYIDX12:%.*]] = getelementptr inbounds i32, ptr [[PDST]], i64 [[ADD11]]
; CHECK-NEXT:    store i32 [[OR]], ptr [[ARRAYIDX12]], align 4
; CHECK-NEXT:    [[AND13:%.*]] = lshr i32 [[CONV2]], 1
; CHECK-NEXT:    [[SHR14:%.*]] = and i32 [[AND13]], 31
; CHECK-NEXT:    [[ADD15:%.*]] = or i64 [[I_071]], 2
; CHECK-NEXT:    [[ARRAYIDX16:%.*]] = getelementptr inbounds i32, ptr [[PDST]], i64 [[ADD15]]
; CHECK-NEXT:    store i32 [[SHR14]], ptr [[ARRAYIDX16]], align 4
; CHECK-NEXT:    [[AND17:%.*]] = shl nuw nsw i32 [[CONV2]], 4
; CHECK-NEXT:    [[SHL18:%.*]] = and i32 [[AND17]], 16
; CHECK-NEXT:    [[SHR19:%.*]] = lshr i32 [[CONV4]], 4
; CHECK-NEXT:    [[OR20:%.*]] = or i32 [[SHL18]], [[SHR19]]
; CHECK-NEXT:    [[ADD21:%.*]] = or i64 [[I_071]], 3
; CHECK-NEXT:    [[ARRAYIDX22:%.*]] = getelementptr inbounds i32, ptr [[PDST]], i64 [[ADD21]]
; CHECK-NEXT:    store i32 [[OR20]], ptr [[ARRAYIDX22]], align 4
; CHECK-NEXT:    [[AND23:%.*]] = shl nuw nsw i32 [[CONV4]], 1
; CHECK-NEXT:    [[SHL24:%.*]] = and i32 [[AND23]], 30
; CHECK-NEXT:    [[SHR25:%.*]] = lshr i32 [[CONV6]], 7
; CHECK-NEXT:    [[OR26:%.*]] = or i32 [[SHL24]], [[SHR25]]
; CHECK-NEXT:    [[ADD27:%.*]] = or i64 [[I_071]], 4
; CHECK-NEXT:    [[ARRAYIDX28:%.*]] = getelementptr inbounds i32, ptr [[PDST]], i64 [[ADD27]]
; CHECK-NEXT:    store i32 [[OR26]], ptr [[ARRAYIDX28]], align 4
; CHECK-NEXT:    [[AND29:%.*]] = lshr i32 [[CONV6]], 2
; CHECK-NEXT:    [[SHR30:%.*]] = and i32 [[AND29]], 31
; CHECK-NEXT:    [[ADD31:%.*]] = or i64 [[I_071]], 5
; CHECK-NEXT:    [[ARRAYIDX32:%.*]] = getelementptr inbounds i32, ptr [[PDST]], i64 [[ADD31]]
; CHECK-NEXT:    store i32 [[SHR30]], ptr [[ARRAYIDX32]], align 4
; CHECK-NEXT:    [[AND33:%.*]] = shl nuw nsw i32 [[CONV6]], 3
; CHECK-NEXT:    [[SHL34:%.*]] = and i32 [[AND33]], 24
; CHECK-NEXT:    [[SHR35:%.*]] = lshr i32 [[CONV8]], 5
; CHECK-NEXT:    [[OR36:%.*]] = or i32 [[SHL34]], [[SHR35]]
; CHECK-NEXT:    [[ADD37:%.*]] = or i64 [[I_071]], 6
; CHECK-NEXT:    [[ARRAYIDX38:%.*]] = getelementptr inbounds i32, ptr [[PDST]], i64 [[ADD37]]
; CHECK-NEXT:    store i32 [[OR36]], ptr [[ARRAYIDX38]], align 4
; CHECK-NEXT:    [[AND39:%.*]] = and i32 [[CONV8]], 31
; CHECK-NEXT:    [[ADD40:%.*]] = or i64 [[I_071]], 7
; CHECK-NEXT:    [[ARRAYIDX41:%.*]] = getelementptr inbounds i32, ptr [[PDST]], i64 [[ADD40]]
; CHECK-NEXT:    store i32 [[AND39]], ptr [[ARRAYIDX41]], align 4
; CHECK-NEXT:    [[ADD42]] = add nuw i64 [[I_071]], 8
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i64 [[ADD42]], [[AND]]
; CHECK-NEXT:    br i1 [[CMP]], label %[[FOR_BODY]], label %[[FOR_END_LOOPEXIT:.*]], !llvm.loop [[LOOP7:![0-9]+]]
; CHECK:       [[FOR_END_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[FOR_END]]
; CHECK:       [[FOR_END]]:
; CHECK-NEXT:    ret void
;
entry:
  %and = and i64 %length, -8
  %cmp70.not = icmp eq i64 %and, 0
  br i1 %cmp70.not, label %for.end, label %for.body

for.body:                                         ; preds = %entry, %for.body
  %pSrc.addr.072 = phi ptr [ %incdec.ptr7, %for.body ], [ %pSrc, %entry ]
  %i.071 = phi i64 [ %add42, %for.body ], [ 0, %entry ]
  %incdec.ptr = getelementptr inbounds i8, ptr %pSrc.addr.072, i64 1
  %0 = load i8, ptr %pSrc.addr.072, align 1
  %conv = zext i8 %0 to i32
  %incdec.ptr1 = getelementptr inbounds i8, ptr %pSrc.addr.072, i64 2
  %1 = load i8, ptr %incdec.ptr, align 1
  %conv2 = zext i8 %1 to i32
  %incdec.ptr3 = getelementptr inbounds i8, ptr %pSrc.addr.072, i64 3
  %2 = load i8, ptr %incdec.ptr1, align 1
  %conv4 = zext i8 %2 to i32
  %incdec.ptr5 = getelementptr inbounds i8, ptr %pSrc.addr.072, i64 4
  %3 = load i8, ptr %incdec.ptr3, align 1
  %conv6 = zext i8 %3 to i32
  %incdec.ptr7 = getelementptr inbounds i8, ptr %pSrc.addr.072, i64 5
  %4 = load i8, ptr %incdec.ptr5, align 1
  %conv8 = zext i8 %4 to i32
  %shr = lshr i32 %conv, 3
  %arrayidx = getelementptr inbounds i32, ptr %pDst, i64 %i.071
  store i32 %shr, ptr %arrayidx, align 4
  %and9 = shl nuw nsw i32 %conv, 2
  %shl = and i32 %and9, 28
  %shr10 = lshr i32 %conv2, 6
  %or = or i32 %shl, %shr10
  %add11 = or i64 %i.071, 1
  %arrayidx12 = getelementptr inbounds i32, ptr %pDst, i64 %add11
  store i32 %or, ptr %arrayidx12, align 4
  %and13 = lshr i32 %conv2, 1
  %shr14 = and i32 %and13, 31
  %add15 = or i64 %i.071, 2
  %arrayidx16 = getelementptr inbounds i32, ptr %pDst, i64 %add15
  store i32 %shr14, ptr %arrayidx16, align 4
  %and17 = shl nuw nsw i32 %conv2, 4
  %shl18 = and i32 %and17, 16
  %shr19 = lshr i32 %conv4, 4
  %or20 = or i32 %shl18, %shr19
  %add21 = or i64 %i.071, 3
  %arrayidx22 = getelementptr inbounds i32, ptr %pDst, i64 %add21
  store i32 %or20, ptr %arrayidx22, align 4
  %and23 = shl nuw nsw i32 %conv4, 1
  %shl24 = and i32 %and23, 30
  %shr25 = lshr i32 %conv6, 7
  %or26 = or i32 %shl24, %shr25
  %add27 = or i64 %i.071, 4
  %arrayidx28 = getelementptr inbounds i32, ptr %pDst, i64 %add27
  store i32 %or26, ptr %arrayidx28, align 4
  %and29 = lshr i32 %conv6, 2
  %shr30 = and i32 %and29, 31
  %add31 = or i64 %i.071, 5
  %arrayidx32 = getelementptr inbounds i32, ptr %pDst, i64 %add31
  store i32 %shr30, ptr %arrayidx32, align 4
  %and33 = shl nuw nsw i32 %conv6, 3
  %shl34 = and i32 %and33, 24
  %shr35 = lshr i32 %conv8, 5
  %or36 = or i32 %shl34, %shr35
  %add37 = or i64 %i.071, 6
  %arrayidx38 = getelementptr inbounds i32, ptr %pDst, i64 %add37
  store i32 %or36, ptr %arrayidx38, align 4
  %and39 = and i32 %conv8, 31
  %add40 = or i64 %i.071, 7
  %arrayidx41 = getelementptr inbounds i32, ptr %pDst, i64 %add40
  store i32 %and39, ptr %arrayidx41, align 4
  %add42 = add nuw i64 %i.071, 8
  %cmp = icmp ult i64 %add42, %and
  br i1 %cmp, label %for.body, label %for.end, !llvm.loop !0

for.end:                                          ; preds = %for.body, %entry
  ret void
}

!0 = distinct !{!0, !1}
!1 = !{!"llvm.loop.mustprogress"}