; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -mtriple=unknown -passes=loop-data-prefetch --indirect-load-prefetch=true --prefetch-distance=512 --min-prefetch-stride=4 -S | FileCheck %s

target datalayout = "e-m:e-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128"

; Function Attrs: nofree norecurse nounwind uwtable
define dso_local void @test(i32 %Num, float* nocapture readonly %TargetArray, i32* nocapture readonly %OffsetArray, float* noalias nocapture %TempArray) local_unnamed_addr #0 {
; CHECK-LABEL: @test(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP13:%.*]] = icmp sgt i32 [[NUM:%.*]], 0
; CHECK-NEXT:    br i1 [[CMP13]], label [[FOR_BODY_PREHEADER:%.*]], label [[FOR_COND_CLEANUP:%.*]]
; CHECK:       for.body.preheader:
; CHECK-NEXT:    [[WIDE_TRIP_COUNT:%.*]] = zext i32 [[NUM]] to i64
; CHECK-NEXT:    [[TMP0:%.*]] = sub i64 [[WIDE_TRIP_COUNT]], 1
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.cond.cleanup.loopexit:
; CHECK-NEXT:    br label [[FOR_COND_CLEANUP]]
; CHECK:       for.cond.cleanup:
; CHECK-NEXT:    ret void
; CHECK:       for.body:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ 0, [[FOR_BODY_PREHEADER]] ], [ [[INDVARS_IV_NEXT:%.*]], [[FOR_BODY]] ]
; CHECK-NEXT:    [[TMP1:%.*]] = add i64 [[INDVARS_IV]], 42
; CHECK-NEXT:    [[TMP2:%.*]] = icmp slt i64 [[TMP1]], [[TMP0]]
; CHECK-NEXT:    [[TMP3:%.*]] = select i1 [[TMP2]], i64 [[TMP1]], i64 [[TMP0]]
; CHECK-NEXT:    [[TMP4:%.*]] = add i64 [[INDVARS_IV]], 84
; CHECK-NEXT:    [[TMP5:%.*]] = shl nuw nsw i64 [[INDVARS_IV]], 2
; CHECK-NEXT:    [[TMP6:%.*]] = add i64 [[TMP5]], 168
; CHECK-NEXT:    [[UGLYGEP1:%.*]] = getelementptr i8, ptr [[OFFSETARRAY:%.*]], i64 [[TMP6]]
; CHECK-NEXT:    [[TMP7:%.*]] = shl nuw nsw i64 [[INDVARS_IV]], 2
; CHECK-NEXT:    [[TMP8:%.*]] = add i64 [[TMP7]], 168
; CHECK-NEXT:    [[UGLYGEP:%.*]] = getelementptr i8, ptr [[TEMPARRAY:%.*]], i64 [[TMP8]]
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds float, ptr [[TEMPARRAY]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    call void @llvm.prefetch.p0(ptr [[UGLYGEP]], i32 0, i32 3, i32 1)
; CHECK-NEXT:    [[TMP9:%.*]] = load float, ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds i32, ptr [[OFFSETARRAY]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr inbounds i32, ptr [[OFFSETARRAY]], i64 [[TMP4]]
; CHECK-NEXT:    [[TMP11:%.*]] = getelementptr inbounds i32, ptr [[OFFSETARRAY]], i64 [[TMP3]]
; CHECK-NEXT:    call void @llvm.prefetch.p0(ptr [[UGLYGEP1]], i32 0, i32 3, i32 1)
; CHECK-NEXT:    [[TMP12:%.*]] = load i32, ptr [[ARRAYIDX2]], align 4
; CHECK-NEXT:    [[TMP13:%.*]] = load i32, ptr [[TMP11]], align 4
; CHECK-NEXT:    call void @llvm.prefetch.p0(ptr [[TMP10]], i32 0, i32 3, i32 1)
; CHECK-NEXT:    [[IDXPROM3:%.*]] = sext i32 [[TMP12]] to i64
; CHECK-NEXT:    [[TMP14:%.*]] = sext i32 [[TMP13]] to i64
; CHECK-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds float, ptr [[TARGETARRAY:%.*]], i64 [[IDXPROM3]]
; CHECK-NEXT:    [[TMP15:%.*]] = getelementptr inbounds float, ptr [[TARGETARRAY]], i64 [[TMP14]]
; CHECK-NEXT:    [[TMP16:%.*]] = load i32, ptr [[ARRAYIDX2]], align 4
; CHECK-NEXT:    [[TMP17:%.*]] = load float, ptr [[ARRAYIDX4]], align 4
; CHECK-NEXT:    call void @llvm.prefetch.p0(ptr [[TMP15]], i32 0, i32 3, i32 1)
; CHECK-NEXT:    [[MUL:%.*]] = fmul contract float [[TMP9]], [[TMP17]]
; CHECK-NEXT:    store float [[MUL]], ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], [[WIDE_TRIP_COUNT]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label [[FOR_COND_CLEANUP_LOOPEXIT:%.*]], label [[FOR_BODY]]
;
entry:
  %cmp13 = icmp sgt i32 %Num, 0
  br i1 %cmp13, label %for.body.preheader, label %for.cond.cleanup

for.body.preheader:
  %wide.trip.count = zext i32 %Num to i64
  br label %for.body

for.cond.cleanup:
  ret void

for.body:
  %indvars.iv = phi i64 [ 0, %for.body.preheader ], [ %indvars.iv.next, %for.body ]
  %arrayidx = getelementptr inbounds float, float* %TempArray, i64 %indvars.iv
  %0 = load float, float* %arrayidx, align 4
  %arrayidx2 = getelementptr inbounds i32, i32* %OffsetArray, i64 %indvars.iv
  %1 = load i32, i32* %arrayidx2, align 4
  %idxprom3 = sext i32 %1 to i64
  %arrayidx4 = getelementptr inbounds float, float* %TargetArray, i64 %idxprom3
  %2 = load float, float* %arrayidx4, align 4
  %mul = fmul contract float %0, %2
  store float %mul, float* %arrayidx, align 4
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, %wide.trip.count
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}
